docs/DATABASE.md
docs/SPEC.md

Added the spec document nakajima-san wrote.

add spec document

---

src/components/ItemCard.vue
src/pages/restaurants/menu/_id.vue

Vue の勉強がてら、menu の部分に少し変更を加えています。既に行なっている作業の邪魔になるのであれrば、merge しなくても結構です。
とりあえずは、itemCard を for loop で呼ぶように変更しました。

Itemcard changes

---

functions/package-lock.json
functions/package.json
functions/src/functions/express.ts
functions/tests/express_test.ts
functions/tests/order_test.ts
functions/tests/test_db_helper.ts
functions/tests/test_helper.ts

express周りのテストとexpressとfirestoreの連携実装

Functions test

---

src/pages/r/_restaurantId/index.vue

ユーザ側のデータもdbから取ってくるように徐々にしていきます。
onSnapshotでもたぶん、こんな感じで更新可能ですね。

get restaurant data from db

---

src/pages/index.vue
src/pages/r/_restaurantId/index.vue

ユーザ側のmenuもfirestoreから取ってくるようにしました。
Appetizers, Entreesのカテゴリーの実装がまだなので、とりあえずEntreesに表示するようにしました。
値段と税金がStringで入っていたので、Numberで数値のみ入れる想定に変えています（管理系はまだ）
値段は、セントで入っている想定（日本の場合は円）で、100の場合は$1です。
'$' + (Number(item.price||0) / 100).toFixed(2)
として、表示しています。
税率も%付きの文字列でしたが、これも4.5などの小数の数値を入れるようにします。

get menu data from firestore

---

.gitignore
functions/src/functions/firestore.ts
functions/src/index.ts
src/pages/admin/restaurants/create.vue
src/pages/index.vue
src/plugins/firebase.js

It allows the restaurant owner to register a unique restaurantId for his/her restaurant.

Create Restaurant API

---

lang/en.json
lang/ja.json
src/pages/admin/restaurants/create.vue

エラーメッセージをi18n対応しました。
これから新しくつくるviewに関しては極力i18nを意識して作ってください。
文言は、適当な英文が思いつかない場合には、日本語でも良いので書いていてください。
後で誰かが修正します。

Errormessage i18n

---

functions/src/functions/firestore.ts
lang/en.json
lang/ja.json
src/pages/admin/restaurants/create.vue

レストランのオーナーであることをチェックするようにしました
サーバーサイドのエラーをクライアントで表示するようにしました
ID をサーバーとクライアントで "alreadTaken" に統一しました

Handle server error

---

firestore.rules

adminとuserが認証のなにで判断できるかがわかるように
Firestore rulesのfunctionにしました。
Web側の実装でも参考にしてください。

Modify rules

---

functions/src/functions/firestore.ts

各documentの所有者はuidで統一しているので、こちらも変更しました。

modify restaurant owner parameter

---

src/pages/admin/restaurants/create.vue

restaurantId を data として持つと、JavaScript console に同じ名前の method があるという warning が出るので、それを避けるためにローカルのデータ名のみ変更しました。なぜ、そんな名前の method があるのかは不明ですが、Nuxt が何らかの理由で作っているのだと思います。

renamed restaurantId to rid locally

---

lang/en.json
lang/ja.json
src/pages/admin/restaurants/create.vue

Restaurant ID を登録するページに Buery のスタイルを適用しました。細かなローカリゼーションも追加しています。

Restrautid styles

---

nuxt.config.js
src/assets/scss/main.scss
src/plugins/buefy.js

Buefy をカスタマイズするための変更です（分かりやすいように、あえて赤にしています）。参考にしたのは下のサイトです。
https://medium.com/@mrzueck/adding-bulma-and-buefy-to-nuxt-js-project-and-reassigning-the-default-styles-using-scss-11413b4c8215

Customize buefy

---

src/store/admin/index.js
src/store/user/index.js

JavaScript console に store/admin/index.js と store/user/index.js は object を返す method であるべしというワーニングが出るので、変更しました。参考にしたものは以下の thread です。下の例は、module を使っていませんが、たぶん同じだと思います。
https://github.com/nuxt/nuxt.js/issues/1280

state as method

---

src/components/OrderedItem.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue
src/pages/index.vue

レストランオーナー向けのオーダーページ（ダッシュボード）のスケルトン（中身はなくて、これから実装）です。
URL は /admin/restaurants/{restaurantId}/orders/ になります。

Admin orders

---

firestore.rules
src/components/TitleEditCard.vue
src/components/TitleInput.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue
src/plugins/utils.js

title部分、menu上で新規作成と、既存の編集を作りました。
add titleすると、そのときに空のtitleを作ります。
titleはmenuと別のcollectionを作りました。
また、メニューの順番はrestaurantsのデータにmenuListsとして持たしています。
todoは、メニュー入れ替えと、削除です。
メニュー側でも、新規を作成したときに、menuListsの最後のmenu.idを追加して保存するようにしてください。

add new title edit mode

---

src/components/TitleCard.vue
src/components/TitleInput.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue

up down menu title

---

src/components/ItemEditCard.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue

support up down on menu item

---

lang/en.json
lang/ja.json
src/components/BackButton.vue
src/components/OrderedItem.vue
src/pages/admin/restaurants/_restaurantId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

各ページで使える back-button component を作りました。<back-button url="/admin/restaurants" /> 
admin/restaurants/_restaurantId/orders ページの実装を進めました
admin/restaurants/_restaurantId/orders/_orderId ページを作りました（中身は空）
admin/restaurants/_restaurantId ページを作りました（中身は空）

More orders

---

lang/en.json
src/components/OrderInfo.vue
src/pages/r/_restaurantId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

add customerOrder

---

src/pages/admin/restaurants/_restaurantId/menus/new.vue

menuを追加したときに、restaurants.menuListsにkeyをpushする部分を追加しました。

push menu item to menu lists

---

lang/en.json
lang/ja.json
src/components/OrderStatus.vue
src/components/OrderedItem.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

管理側でオーダーの一覧を見るための画面（ダッシュボード）の実装です。実装途中ですが、とりあえずキリが良いところまで出来たのでマージします。

Orders from db

---

src/pages/r/_restaurantId/index.vue

ユーザー用のオーダーページを見ていて思ったのですが、orderItems  は menus と orderInfo を watch して updateOrder() で計算していますが、それであれば、orderInfo を comupted プロマティにした方がバグが出にくいと思うのです。とりあえず参考までに PR を作ってみました。表示は確認しました、menu などの変化にちゃんと対応するかどうかは確認していません。

computed property

---

src/pages/r/_restaurantId/index.vue

itemsObjの更新が抜けていたのと、varをconstに変える変更をしました。
動くようになりました。

fix menu lists

---

firestore.rules
lang/en.json
src/assets/scss/customize.scss
src/assets/scss/main.scss
src/assets/scss/orders.scss
src/components/OrderStatus.vue
src/components/OrderedItem.vue
src/layouts/default.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

Admin 向けの order ページから、オーダーのステータスを変更できるようにしました。

Admin order

---

lang/en.json
src/layouts/default.vue
src/pages/index.vue
src/pages/test/sms.vue
src/plugins/firebase.js

独立したコードですが、SMSでのログインが出来るところまで確認できました。

Sms signin

---

lang/en.json
src/pages/test/sms.vue

Use select for the country code
Validations
UI tweak

Sms signin 2

---

src/components/auth/PhoneLogin.vue
src/layouts/default.vue
src/pages/test/sms.vue

1. Implemented "Sign Out"
2. Display phone number on test/sms page when the user is logged on
3. A few clean-up in default.vue

Implemented "Sign Out"

---

src/components/LoginModal.vue
src/components/ShopInfo.vue
src/pages/r/_restaurantId/index.vue

A few cleanup

---

lang/en.json
lang/ja.json
src/pages/admin/restaurants/_restaurantId/edit.vue
src/plugins/constant.js

set Business day

---

firestore.rules
lang/en.json
lang/ja.json
src/components/OrderInfo.vue
src/components/OrderItem.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Implemented the order page more, still in progress. 
まだ途中ですが、オーダーページの実装を進めました
- ローカリゼーション
- 不要な prop の削除
- specialRequest の扱い（これは実装途中）
- Edit Menu （実装中：とりあえず、注文を削除出来るようにしました）

Order Page Implementation

---

src/components/ItemEditCard.vue
src/components/TitleCard.vue

aタグをクリックしたときにページが動かないように変更。
@click.prevent つけるだけなのですね。

don't move page

---

src/layouts/default.vue
src/pages/admin/restaurants/index.vue
src/pages/admin/user/signin.vue
src/pages/admin/user/signup.vue
src/pages/r/_restaurantId/index.vue
src/pages/test/sms.vue
src/plugins/userPermission.js
src/plugins/utils.js
src/store/index.js

結構、大きな変更です。一通りテストはしました。
store から firebase のコードを外しました（UI側に移しました）
store/admin, store/user を廃止して（まだコードは rm していません）、単に store に user をしまうようにしました。
使われていない totalOrderCount を store から外しました

Simple store

---

firestore.rules
src/components/ItemEditCard.vue
src/components/TitleCard.vue
src/pages/admin/restaurants/_restaurantId/edit.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue
src/pages/admin/restaurants/_restaurantId/menus/new.vue

メニュー一覧からmenuとtitleを削除可能に。
deletedFlagを追加しました。

delete menu item

---

firestore.rules
src/components/ItemEditCard.vue
src/components/TitleCard.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue

fork titleの実装と、先程の修正を含めた不具合の修正もしました。

fork title

---

src/pages/admin/restaurants/_restaurantId/menus/index.vue
src/pages/admin/restaurants/_restaurantId/menus/new.vue

fork menu item

---

src/pages/admin/restaurants/_restaurantId/menus/index.vue
src/pages/admin/restaurants/index.vue

readyToDisplay flag を導入することにより、非同期オペレーション中に 0 restaurant などが表示されないようにしたものです。

readyToDisplay flag

---

src/pages/r/_restaurantId/index.vue

location hashでaboutとmenuを切り替え対応。

add location hash link on customer menu

---

package-lock.json
src/components/ItemCard.vue

orderのボタンを削除して、item cardをクリックするとオーダー画面が開くようにしました。

remove order button

---

src/layouts/default.vue
src/pages/test/sms.vue
src/store/index.js

$store.state.date に new Date() を置き、１分ごとにアップデートするようにしました。

Store timer

---

src/pages/r/_restaurantId/index.vue

removed warnings

---

src/assets/scss/main.scss
src/assets/scss/okajima.scss
src/components/ShopInfo.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Added ShopInfo to the order page.
Added "compact" flag to ShopInfo.
Introduction of Okajima.css (just the beginning)

ShopInfo on the thank you page

---

src/assets/scss/_mixins.scss
src/assets/scss/okajima.scss
src/components/ItemCard.vue
src/components/ItemEditCard.vue
src/components/ShopInfo.vue
src/components/ShopOrnerInfo.vue
src/pages/r/_restaurantId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Okajima Design

---

functions/src/functions/firestore.ts
src/components/OrderedInfo.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/plugins/strings.js

Introduced the concept of "order name", which is not universally unique, but unique enough to verify during the pick-up process (such as #003). 
The restaurant object has a property "orderCount". The cloud function atomically increments it when a new order document is created, and assign its value as the "number" property of the order object.

Order name

---

src/components/OrderedInfo.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/plugins/firebase.js

This is a temporary code to add user's phone number and the timestamp to the order object when the user complete the order. Once we integrate Stripe, this operation should be done on the server side.

Order info

---

functions/tests/order_test.ts

order counterのfunctionsにtestを追加しました。

add order counter test

---

package-lock.json
package.json
src/components/OrderedInfo.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/plugins/phoneutil.js

The order list and order page for restaurant owners displays the time (paid time) the phone number of the user associated with each order. 
The phone number of order page is "tel:" hyperlink for smartphones (not tested).

Phone number

---

src/pages/r/_restaurantId/index.vue

Please notice that we need to change emitted() method as well so that it properly update computed properties.

foodCounter as a computed property

---

functions/package-lock.json
functions/package.json
functions/src/functions/firestore.ts
functions/tests/order_test.ts

料金計算するようにしました。
menu.taxの形式がまだ変更に追従していないので
税金計算は間違った値が返ってくることがあります。
他は正しく計算されるはずです。

Calculate order

---

functions/src/functions/firestore.ts
functions/tests/order_test.ts

存在しないメニューを注文した場合などにエラーになるので、
それをハンドルして、statusをエラーにするようにしました。
これで、validationは不要ですね。

add error handle.

---

src/pages/r/_restaurantId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/store/index.js

Edit order

---

package-lock.json
src/components/NotFound.vue
src/pages/r/_restaurantId/index.vue

not foundのページを追加。
ページデザインと、他のところでも同様にサポートしていきましょう。

add not found page

---

lang/en.json
lang/ja.json
src/components/RestaurantEditCard.vue
src/pages/admin/restaurants/index.vue

Cleanup restaurants

---

lang/en.json
lang/ja.json
src/pages/admin/user/reset.vue
src/pages/admin/user/signin.vue
src/pages/admin/user/signup.vue

Implemented the "password reset" feature.

Password reset

---

src/pages/r/_restaurantId/index.vue

go 404 if publicFlag is false

---

functions/src/checkout/index.ts
src/pages/r/_restaurantId/order/_orderId/index.vue

implement error handling 

---

nuxt.config.js
src/components/StripeCard.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/plugins/stripe.js

stripe と firebase に関していくつかwarningが出ていたので、修正しました。stripe スクリプトは nuxt.config.js で読み込むようにし、Stripe インタンスは、plugins/stripe.js で作って返すようにしました。APIは後にこちらに移動する予定です。

Remove warnings

---

src/pages/admin/restaurants/_restaurantId/menus/_menuId/index.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

menu listをcomputedとonSnapshotで書き換えました。

cleanup menu lists

---

src/pages/admin/restaurants/_restaurantId/menus/index.vue

clean up menu lists

---

src/pages/admin/restaurants/_restaurantId/index.vue
src/pages/admin/restaurants/_restaurantId/menus/index.vue

add not found on admin page

---

src/pages/admin/restaurants/_restaurantId/index.vue

fix google map place link

---

lang/en.json
src/pages/admin/restaurants/_restaurantId/menus/_menuId/index.vue

add item option checkbox

---

lang/en.json
src/assets/scss/customize.scss
src/assets/scss/okajima.scss
src/assets/scss/orders.scss
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/plugins/constant.js

Made it possible to cancel the order from the order screen (by admin)

Cancel order

---

src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/all.vue

Cancel order (2)

---

src/pages/r/_restaurantId/index.vue

fix checkout btn layout

---

src/components/ItemCard.vue
src/pages/r/_restaurantId/index.vue

Uses item object property instead of various props.
Fixed background color bug

Item card cleanup

---

src/components/ItemCard.vue
src/pages/r/_restaurantId/index.vue

Displays order options as checkbox (choice=1), or radio buttons (chose > 2)
This is just UI change, not database change yet.

Order Options UI

---

src/components/ItemCard.vue
src/components/OrderedItem.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/r/_restaurantId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/store/index.js

1. Store options to the database (order object)
2. Inherit it via store if the user chooses to edit the order
3. Present it to the admin (restaurant operator)

Option values

---

src/components/RestaurantEditCard.vue
src/pages/admin/restaurants/index.vue

レストランの論理削除です。
firestoreはnot equalで検索できないので、フラグ系は最初に洗い出して、falseで入れておく必要がありますね。今後は気をつけましょう。

support to delete restaurants

---

src/pages/r/_restaurantId/order/_orderId/index.vue

Fixed the brief display of 404 Error after selecting the Edit Items on the order page.

fix 404 on Edit Items

---

firestore.rules
src/components/RestaurantEditCard.vue
src/pages/admin/restaurants/create.vue
src/pages/admin/restaurants/index.vue

When creating a new restaurant, it assigns the restaurant ID automatically.

Auto restaurantId

---

lang/en.json
lang/ja.json
src/pages/r/_restaurantId/order/_orderId/index.vue

Added "Place Order without Payment" button to the order page (for beta testing).

place order without payment

---

src/components/OrderedInfo.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

Admin's orders pages shows todays' orders. (We will add a date picker later)

Orders page

---

lang/en.json
lang/ja.json
src/components/OrderedInfo.vue
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Updated the thank you page with the "check" icon and additional message.

User: Thank you page

---

lang/en.json
lang/ja.json
src/pages/admin/restaurants/index.vue

Show the "under construction" at Payment page when "hidePayment" flag is on.

no payment for admin

---

lang/en.json
lang/ja.json
src/pages/about.vue
src/pages/admin/restaurants/_restaurantId/menus/_menuId/index.vue

Added a help text to the item options.

Options note

---

src/pages/admin/restaurants/_restaurantId/menus/index.vue

disabled button when add item/title click

---

src/components/ItemCard.vue

Fixed an empty checkbox bug with empty itemOptionCheckbox string.

fix empty checkbox bug

---

nuxt.config.js
src/pages/about.vue

about画面をみると、デプロイ時の最終コミットがconsoleにでる。

show last commit hash

---

README.md
src/components/RestaurantEditCard.vue

add share url

---

nuxt.config.js
package-lock.json
package.json
src/components/user/SharingButtons.vue
src/components/user/ShopOrnerInfo.vue
src/plugins/social.js

Added Facebook/Twitter button to the restaurant's menu page.

Social sharing

---

src/pages/admin/restaurants/index.vue

http call の呼び方が間違って失敗していたので、修正しました。

make it callable

---

README.md
functions/src/index.ts
functions/src/stripe/checkout/index.ts
functions/src/stripe/index.ts
src/components/StripeCard.vue
src/pages/r/_restaurantId/order/_orderId/index.vue
src/plugins/stripe.js

https://stripe.com/docs/connect/direct-charges

Fix stripe account for Direct charge

---

functions/src/stripe/index.ts
src/pages/admin/restaurants/index.vue

Passing STRIPE_CLIENT_ID from client (not from server's environment)

pass client_id from client

---

lang/en.json
lang/ja.json
src/pages/admin/restaurants/index.vue

Fixed issues associated with this.paymentItems.
Fixed UI issues associate with Connect and Disconnect.

Has stripe

---

README.md
nuxt.config.js
src/pages/admin/restaurants/index.vue

update stripe configs

---

src/assets/scss/customize.scss
src/components/StripeCard.vue
src/pages/admin/restaurants/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Admin: Display loading animation while disconnecting.
User: Display loading animation while processing payment
User: Disable the "pay" button until all the required fields are filled.

Stripe: Various UI improvement

---

firestore.indexes.json
firestore.rules
functions/src/functions/order.ts
functions/src/index.ts
functions/src/stripe/checkout/index.ts
src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue
src/pages/admin/restaurants/_restaurantId/orders/index.vue

It allows admin to update the status of order. 
I made some changes to firestore.rules to prevent it updated from the client side.
Updated the indexes file appropriately.

cloudFunction: orderUpdate 

---

.circleci/config.yml
firebase.json

update deploy script

---

firestore.rules
functions/src/functions/order.ts
functions/src/stripe/checkout/index.ts
src/pages/r/_restaurantId/index.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

1. Added phoneNumber at the creation of the order document (must match uid.phoneNumber).
2. Added createdAt to the order document
2. orderUpdate: Changed set to update

order phoneNumber

---

README.md
lang/en.json
lang/ja.json
nuxt.config.js
package-lock.json
package.json
src/components/RestaurantEditCard.vue
src/plugins/clipboard2.js

copy share url to clip board

---

lang/en.json
lang/ja.json
src/components/user/OrderInfo.vue
src/pages/r/_restaurantId/order/_orderId/index.vue

Enable tip

---

.circleci/config.yml
.gitignore
README.md
package.json
src/config/default/ownplate-dev.js
src/config/default/ownplate-jp.js
src/config/default/ownplate.js
src/plugins/config.js
src/plugins/firebase.js

1. Renamed firebase.js to project.js in src/config
2. Removed default export from project.js (and default files)
3. Separated ownPlateConfig from firebaseConfig and exported it separately
4. Modified package.json to copy config files to project.js
5. Modified README file
6. Modified CI script (not tested)

Refactoring: project.js

---

functions/src/index.ts
functions/src/stripe/index.ts
src/app/admin/OwnerPage.vue
src/app/user/OrderPage.vue
src/plugins/stripe.js

This is the step 1 of refactoring of functions. Mostly renames.

Refactoring functions

---

functions/src/stripe/intent.ts
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue

When admin switch the status to "Complete", it will call stripeConfirmIntent to complete the payment.

Order confirm

---

functions/src/stripe/intent.ts
functions/src/stripe/oauth.ts
functions/src/stripe/utils.ts
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue

1. Made it easy to read
2. Replaced orderPath param to restaurantId and orderId

Stripe cleanup 1

---

firestore.rules
functions/src/stripe/intent.ts
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue

It stores stripe's payment info in the system area of the database (including payment intentId).
It simply stores {stripe:true} as the payment property of the (public) order document.
It displays the stripe icon next to the price in the order list view and order details view for admin.

Stripe cleanup #2

---

functions/src/stripe/intent.ts

don't store result

---

package-lock.json
package.json
src/app/admin/OrderInfoPage.vue
src/app/admin/OrderListPage.vue

管理系のオーダーで、日付情報をリンクに含め、ブラウザのhistoryにも対応しました。

fix admin order page link

---

functions/src/functions/order.ts
functions/src/models/Order.ts
lang/en.json
lang/ja.json
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue

orderUpdate で order.status を変えられるルールを設定しました（ここはテストが必要だと思います）。
UI側もそれに合わせて、ボタンを enable/disable しました。

Stripe cleanup 4

---

functions/src/functions/firestore.ts
functions/src/stripe/intent.ts
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue
src/plugins/stripe.js

ユーザーが指定したTipを加えて、チャージするようにしました。
Stripe API の名前を、サーバーとクライアントで一致させました
四捨五入を正しくやるようにしました。

Stripe cleanup 5

---

firestore.rules
functions/src/functions/order.ts
functions/src/index.ts
src/app/user/OrderPage.vue

It now supports customers who want to pay at the restaurant without firestore hack.
It also supports tips for those customers.

Support non-paying customer

---

functions/src/functions/firestore.ts
functions/src/functions/order.ts
functions/src/stripe/intent.ts
functions/src/stripe/utils.ts
src/plugins/constant.js

1. It passes region specific currency (USD, JPY, ...) to Sprite
2. It uses region specific multiplier (100 for USD, 1 for JPY) to Sprite
3. It uses the same multiplier to round numbers. 
3.333USD => 3.33USD
3.333JPY => 3JPY

Functions: support multiple regions

---

functions/src/stripe/intent.ts
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue
src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

Made it possible for the user to cancel order (in case of no payment transaction).
Simplified return values from the strip functions on the server side.

User: Cancel without payment

---

src/app/user/OrderPage.vue

Add  order page authorization.
Update share url.

Check user

---

src/app/admin/AboutPage.vue

fix don't  save restaurant info draft  data

fix draft don't save

---

src/app/admin/MenusPage.vue

fix broken menu list

---

CONFIGURATIONS.md

I add document for server and client configuration.
If you add new configuration or environment variables , please update here.

add configurations document

---

functions/src/functions/sms.ts

fix lint error.
https://circleci.com/api/v1.1/project/github/Nakajima-Foundation/ownplate/357/output/114/0?file=true&allocation-id=5ea4e9295f08aa50e167a6f8-0-build%2F43F1B3D4

fix invalid return type

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/RestaurantPage.vue

fix default quantity set 0.
fix open/close status in Quantity menu  when user back from checkout page.

fix default quantity set 0

---

src/app/user/Restaurant/ShopInfo.vue

fix business ours

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/RestaurantPage.vue

prop は read-only なので、変更すると変なことになります（コンソールに warning が出ます）。そこで initialOpenMenuFlag として初期状態を渡すように変更しました。

prop is readonly

---

src/app/user/Restaurant/ItemCard.vue

radio button の name がちゃんと生成されていないため、全部が一つのグループとして扱われrてしまうというバグがあったので、修正しました。

fix radio button bug

---

src/plugins/constant.js

region specific required allergens

---

src/app/admin/AboutPage.vue

The save button is fixed bottom of page.

update save button on admin restaurant page

---

src/app/user/Restaurant/ItemCard.vue

clean up open toggle

---

src/app/admin/Restaurant/RestaurantEditCard.vue
src/app/auth/ResetPasswordPage.vue
src/app/auth/SignInPage.vue
src/app/auth/SignUpPage.vue
src/app/user/RestaurantPage.vue
src/app/user/RootPage.vue
src/components/BackButton.vue
src/layouts/default.vue

remove localePath link

---

src/app/admin/AboutPage.vue
src/layouts/default.vue
src/plugins/constant.js

support logo

---

firestore.indexes.json
firestore.rules
nuxt.config.js
src/app/user/OrderHistory.vue
src/app/user/Restaurant/ShopInfo.vue

Order history

---

lang/en.json
lang/ja.json
src/app/admin/Order/OrderedInfo.vue
src/app/user/OrderHistory.vue
src/layouts/default.vue

1. detacher をしまうのを忘れていたので、修正しました。
2. ユーザーとしてログインしている時には、メニューから "Order History" ページを開けるようにしました
3. Order History 上の Order リストの表示をオーナー向けのものと少し変えました（レストラン名の表示、日付の表示）

Order history2

---

lang/en.json
lang/ja.json
src/config/default/ownplate-dev.js
src/layouts/default.vue
src/plugins/config.js

It displays a warning when the user is visiting our staging server.

under construction

---

src/app/admin/AboutPage.vue

1. Added the validation of web-site URL (very simple regular expression)
2. Removed duplicated type
3. Replaced most of is-white with is-success (to be consistent)

validate url

---

firestore.indexes.json
firestore.rules
functions/src/index.ts
nuxt.config.js
src/app/super/AllOrders.vue
src/app/super/SuperHome.vue
src/app/user/OrderPage.vue
src/layouts/default.vue
src/pages/index.vue
src/routes.js
src/store/index.js

1. Created an admin page for super user (real admin)
2. Make "all orders" page for super user
3. Moved customRoutes out from nuxt config file

Super user page

---

src/app/admin/OrderInfoPage.vue
src/plugins/phoneutil.js

店用のオーダーページに日本の電話番号を表示する場合に、0を先頭に追加したものです。tel: リンクの方にも追加します。

add prefix 0 for Japan

---

src/app/admin/Order/OrderedInfo.vue

fix restaurant name layout issue

---

src/app/user/Order/OrderInfo.vue
src/plugins/constant.js

Fix jpy tip

---

src/app/admin/AboutPage.vue
src/app/user/Restaurant/ShopInfo.vue
src/components/PhoneEntry.vue
src/config/default/ownplate-eu.js

店の電話番号の正規化をしています。
phoneNumber に加えて、countryCode をレストラン情報に追加しました。
客向けに表示する際には、正規化したものを表示しています。
EU向けをちゃんとやるのは少し複雑なので、多少の準備はしてありますが、今回は見送ります。

Phone validation

---

src/layouts/default.vue

Add "wrapper" and "main" tag so that the footer will stick to the bottom even though the main contents area is shorter than the window size.

Sticky Footer

---

lang/en.json
lang/ja.json
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderInfoPage.vue
src/app/user/Order/TimeToPickup.vue
src/app/user/OrderPage.vue

Time to pickup #2

---

lang/en.json
lang/ja.json
src/components/Price.vue

tax in small font

---

src/app/user/RestaurantPage.vue

Checkout のリトライを３回（トータルで４回）するように変更しました。
リトライするのは、error.code が permission-denied の場合のみです。
リトライごとに 0.5 秒待っています。

retry checkout

---

lang/en.json
lang/ja.json
src/app/user/Order/TimeToPickup.vue
src/app/user/OrderPage.vue

店の開店時間が少なく、注文出来ない場合の処理を実装しました。

not available

---

nuxt.config.js
package-lock.json
package.json
src/config/default/ownplate-dev.js
src/config/default/ownplate-jp.js
src/config/default/ownplate.js
src/plugins/sentry.js

sentry追加。
setTimeout(() => { throw new Error("sample error"); }, 0);
で、例外起こすと、sentyのwebでエラー内容が見れることを確認。

add sentry

---

src/assets/scss/ownplate.scss
src/layouts/default.vue

フッターのスタイルを整えたのと、言語設定ダイアログのプレースホルダーを追加しました。言語設定の機能部分のアップデートお願いします（もしくは対応するまで非表示）。

Update footer style and put placeholder for language selector.

---

lang/en.json
lang/ja.json
src/layouts/default.vue
src/plugins/constant.js

set Language

---

src/app/user/RootPage.vue
src/assets/scss/ownplate.scss
src/layouts/default.vue

Fix .main container width issue with additional child container(.contents).

Fix .main container width issue.

---

.gitignore
docs/CONFIGURATIONS.md
functions/package-lock.json
functions/package.json
functions/src/functions/express.ts
functions/src/index.ts

FunctionsにもSentryを仕込みました。
設定はFunctionsの環境変数に設定済みです。
マージしてデプロイすると使えます。

Sentry functions

---

functions/src/functions/line.ts
functions/src/index.ts
functions/src/lib/netutils.ts
src/config/default/ownplate-dev.js
src/config/default/ownplate-jp.js
src/pages/test/line.vue

Line login のコードをまずはテストページで開発しています。
サーバー側で custom token を作り、クライアント側でログインするところまで動いています。

Test Code: Line Login

---

functions/src/functions/sms.ts

一時的にsmsのタイトルをomochikaeriにしました。
本来は設定ファイルを参照すべき。

modify title

---

src/app/user/Order/OrderInfo.vue

https://app.asana.com/0/1170889733817798/1176155129971937/f

fix tip bug over 10000

---

src/app/user/Common/SharingButtons.vue
src/app/user/Restaurant/ItemCard.vue
src/pages/about.vue

ItemCardにAddボタンを追加しました。現状Addボタンをタップするたびにカードが開閉してしまうので、カードが閉じている時にAddでアイテム追加とカードを開き、カードが開いた状態でAddしたらアイテムは追加されるけどカードは閉じないようにしたいです。

Add "Add" button to the item card.

---

functions/src/functions/express.ts
functions/src/functions/order.ts
functions/src/stripe/intent.ts
src/config/default/ownplate-dev.js
src/config/default/ownplate-eu.js
src/config/default/ownplate-jp.js
src/config/default/ownplate.js
src/plugins/constant.js

オーダー状態を知らせるメッセージにURLを追加したものです。

Order Notification with url

---

lang/en.json
lang/ja.json
src/app/admin/OwnerPage.vue
src/app/admin/Restaurant/RestaurantEditCard.vue
src/assets/scss/ownplate.scss

オーナー向けトップページに新しいレイアウトを適用しました。
メインの導線である「オーダー確認」へのボタン周りをすっきりさせるため、シェア機能と店情報は公開先のページへリンクして確認してもらうようにしました。

New layout for Owner Top page.

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

Move restaurant description to under restaurant name.

---

src/app/user/Restaurant/SharePopup.vue
src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

シェア用のポップアップを店情報のコンポーネントから独立させました。

Extract Share Popup from ShopInfo and Make a component.

---

nuxt.config.js
package.json

add plugin-proposal-optional-chaining

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/ShopHeader.vue

Auto crop css for upload image.

---

lang/en.json
lang/ja.json
src/app/user/OrderPage.vue

Added the "View Menu" button at the bottom of the order page.

View Menu button to the order page

---

lang/en.json
lang/ja.json
src/app/user/OrderPage.vue
src/assets/scss/ownplate.scss

View Menuボタンを店情報の下から注文詳細に移動してデザインを少し変更しました。

Move "View Menu" button under the order details and minor design update

---

lang/en.json
lang/ja.json
src/app/admin/Menus/ItemEditCard.vue
src/app/admin/Menus/TitleCard.vue
src/app/admin/Menus/TitleInput.vue
src/app/admin/MenusPage.vue
src/app/admin/OwnerPage.vue
src/components/BackButton.vue

New layout for Owner Menu List page.

---

src/app/admin/AboutPage.vue
src/app/admin/MenuItemPage.vue
src/app/admin/Menus/ItemEditCard.vue
src/app/admin/Order/OrderedItem.vue
src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/ShopHeader.vue

以下エラーに対する修正です。
> undefined is not an object (evaluating '_this$menuitem$images2.resizedImages["600"]')

Fix image() in ItemEditCard.

---

src/app/admin/Menus/ItemEditCard.vue
src/app/admin/Menus/TitleCard.vue
src/app/admin/Menus/TitleInput.vue

Use new alert system instead of browser's confirm API.

More alert

---

src/app/user/Restaurant/ShopInfo.vue

change address notation in Japan

---

src/app/user/TransactionsAct.vue
src/routes.js

特定商取引法に基づく表記のベース作りました。
/r/:restaurantId/transactionsAct
のurlで確認できるので、デザインをお願いします。

特定商取引法に基づく表記

---

src/app/admin/MenuItemPage.vue
src/app/admin/RestaurantPage.vue
src/app/admin/inputComponents/HoursInput.vue
src/app/admin/inputComponents/State.vue
src/app/admin/inputComponents/TextForm.vue
src/assets/scss/ownplate.scss

オーナー向けレストラン詳細編集ページの新レイアウト対応です。

New layout for Owner Restaurant Edit page.

---

src/app/user/RestaurantPage.vue

以前あった resizedImages の問題で["1200"]の方は未対応でしたので修正しました。

Fix resizedImages for ["1200"]

---

lang/ja.json
src/app/user/Profile.vue
src/layouts/default.vue
src/routes.js
src/store/index.js

ログインの仕方が３通り（email, phone, line）になったので、デバッグの意味も含めてプロフィールページを作りました（メニューからのリンクはまだ貼っていません）。

User Profile Page

---

lang/ja.json

Update some texts.

---

lang/en.json
lang/ja.json
src/app/trace/Record.vue
src/app/user/OrderPage.vue
src/app/user/Profile.vue
src/layouts/default.vue
src/store/index.js

プロフィール関連の細かな変更です。
1. プロフィールページへの変更
1-1. 「注文履歴」リンクを追加
1-2. 「飲食店としてサインイン」のリンクを追加
1-3. プロフィール画面から友達設定をした直後に表示がアップデートされない問題を解決
2. メインメニューへの変更
2-1. プロフィールページへにリンクを追加
2-2. メインメニューから「サインアウト」の削除（プロフィールページから可能）
2-3. メインメニューから「注文履歴」を削除
3. バグの修正
3-1. LINEとの連携済みの人に連携ボタンが表示されてしまうバグを修正
3-2. 入店・退店記録のページで、undefined になってしまうバグを修正

Profile #3

---

lang/en.json
lang/ja.json
src/app/admin/Order/OrderStatus.vue
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderListPage.vue
src/assets/scss/orders.scss
src/assets/scss/ownplate.scss

オーナー向けオーダー一覧ページの新レイアウト対応です。この変更でユーザー側の注文履歴のタブレットレイアウトに影響が出ていますが、追ってそちらもアップデートする予定です。

New Layout for Owner Order List page

---

lang/en.json
lang/ja.json
src/app/admin/Order/OrderStatus.vue
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderListPage.vue
src/app/user/OrderHistory.vue
src/assets/scss/orders.scss
src/assets/scss/ownplate.scss

ユーザーの注文履歴の新レイアウト対応です。
戻るボタンを追加してプロフィールページ（/u/profile）へリンクしました。

New Layout for User Order History page

---

firestore.indexes.json
firestore.rules
lang/en.json
lang/ja.json
src/app/admin/QRCodePage.vue
src/app/admin/TraceList.vue
src/routes.js

レストランオーナーが、自分の店の入退店記録を見ることが出来るようにしました。
そのページへリンクは、QRcode ページの一番下に置きました。

COVID-19: Trace List for Restaurant Owners

---

src/config/default/ownplate-dev.js
src/config/default/ownplate-jp.js
src/plugins/firebase.js
src/plugins/header.js

add analytics

---

batch/migrate_payment.js
functions/src/stripe/oauth.ts
lang/en.json
lang/ja.json
package.json
src/app/admin/Payment/PaymentSection.vue
src/app/user/OrderPage.vue

課金ありなしに関わらず、店側が「お店で支払う」ことを可能にするかどうかをコントロールできるようしました。それを可能にするために、データベースの構造を少し変更しました (public/stripe -> public/payment)。将来、他のペイメントもこれでサポートしやすくなります。

In-store payment

---

batch/template.js

メモリを大量に使わずにバッチを走らせるためのテンプレートです。

Batch template

---

functions/src/stripe/intent.ts

use public/payment instead of public/stripe

---

lang/en.json
lang/ja.json
src/app/admin/RestaurantPage.vue

Person name

---

lang/en.json
lang/ja.json
src/app/user/Restaurant/ShopInfo.vue
src/app/user/TransactionsAct.vue

「特定商取引法に基づく表記」に関するリンクとページを追加しました。UX的にも実装的にもポップアップ表示の方が良さそうだったので<b-modal>を使用しています。
＜運営責任者＞部分の埋め込みをよろしくお願いします。

Add Transactions Act page(popup).

---

src/app/user/OrderPage.vue

Code Review で指摘された余計な if 文の削除です。

removed unnecessary if

---

src/app/auth/PhoneLogin.vue
src/app/user/Profile.vue

Account を delete する際、ログインしてからしばらく経っているとが user.delete() が失敗する仕様なので（firebase の仕様）、同じ電話番号で再ログインをリクエストするようにしました。

Ask the user to re-login when deleting an account

---

src/app/user/Order/TimeToPickup.vue

Time to Pickup > Not Available部分のデザインを微調整しました。

Minor design update.

---

lang/en.json
lang/ja.json
src/app/admin/OrderListPage.vue
src/layouts/default.vue

サウンドがならないという、トラブルがよくあるので、テストボタンを追加しました。
仮でおいたので、デザインの調整をお願いします。

add sound test button

---

functions/src/functions/order.ts
src/app/user/OrderPage.vue

レストラン側でメニューの内容や値段を変更しても、過去のオーダーページはオーダーした時のままの情報を表示するように変更しました。

Handle price change

---

src/app/user/OrderHistory.vue
src/app/user/OrderPage.vue
src/app/user/TransactionsAct.vue

Minor clean up

---

src/app/admin/QRCodePage.vue
src/app/auth/LineCallback.vue
src/app/auth/SignInPage.vue
src/app/auth/SignUpPage.vue
src/app/trace/Record.vue
src/app/user/Order/StripeCard.vue
src/app/user/OrderPage.vue
src/app/user/Profile.vue
src/app/user/RestaurantPage.vue
src/layouts/default.vue
src/pages/test/line.vue
src/pages/test/sms.vue
src/plugins/utils.js

user() などのよく使われる computed props を plugins/utils に移動しました

Shared computed props

---

src/app/admin/MenuItemPage.vue
src/app/admin/QRCodePage.vue
src/app/admin/RestaurantPage.vue
src/app/admin/inputComponents/State.vue
src/layouts/default.vue
src/pages/index.vue
src/plugins/utils.js

utils の regionalSetting computed prop を利用するように変更しました。data() の中だとアクセスできないので、created からアクセスしてセットしています。

Shared computed props #2

---

lang/ja.json
src/app/admin/Payment/PaymentSection.vue
src/components/DialogBox.vue
src/pages/index.vue

Minor design fix.

---

src/app/trace/Record.vue
src/app/user/OrderPage.vue
src/app/user/Profile.vue
src/plugins/utils.js

Line Login に関して似たようなコードが三箇所にあったので、utils にまとめました。

lineAuthURL in utils

---

src/app/admin/Index.vue

すみません、リリースノート等を記載するニュース一覧ページ（NewsList.vue）とニュース詳細ページ（NewsDetails.vue）の空のtemplateファイルと暫定的なリンク（/news, /news/"newsId"?）お願いしてもよろしいでしょうか？

Adding Release Notes (News) pages.

---

functions/src/lib/utils.ts
functions/tests/order_test.ts

restaurantのpublicFlagチェックと、customer導入にテストが追従していなかったので修正です。

fix functions test

---

src/app/admin/RestaurantPage.vue

fix pickup time

---

src/app/admin/RestaurantPage.vue

fix phone number

---

src/app/admin/Index.vue

News のセクションは開発中なので、v0.5.2 に向けてとりあえず隠します。

hide news section

---

firestore.rules
functions/src/functions/line.ts
functions/src/functions/order.ts
functions/src/lang/en.ts
functions/src/lang/ja.ts
functions/src/stripe/intent.ts
lang/en.json
lang/ja.json
package-lock.json
package.json
src/app/admin/ManageLine.vue
src/app/admin/OrderListPage.vue
src/app/admin/Payment/PaymentSection.vue
src/app/auth/LineCallback.vue
src/app/auth/TrackCallback.vue
src/app/trace/Record.vue
src/app/user/OrderPage.vue
src/app/user/Profile.vue
src/plugins/utils.js
src/routes.js

ラインを使ってレストランのオペレーターに新しいオーダーが入ったことを知らせる仕組みです。
レストランごとに複数のラインのアカウントを追加できるように実装してあります。
それぞれのアカウントに対して、通知のON/OFFが可能です。

Line notification to restaurants

---

src/app/admin/ManageLine.vue
src/app/auth/LineCallback.vue
src/app/auth/TrackCallback.vue
src/app/trace/Record.vue
src/app/user/OrderPage.vue
src/app/user/Profile.vue
src/plugins/line.js
src/plugins/utils.js

line 関連の methods を plugins/utils.js から plugins/line.js に移動しました。

line related methods in line.js

---

src/app/admin/ManageLine.vue
src/app/auth/LineCallback.vue
src/plugins/line.js

レストランオーナーにリンクを踏ませることにより、勝手にラインを連携されてしまうセキュリティ・ホールを塞ぎました。LINE認証の時に使った state （まだ cookie に残っているもの）を userId と一緒に渡すことにより、単にリンクを踏んだだけでは連携できないようにしました。

Line security: Verify state in cookie to make it safe.

---

src/app/user/Restaurants/All.vue

ユーザー向けレストラン一覧ページの「全てのエリア」ページにおけるタブレット表示のレイアウト崩れを修正しました。

Fix the tablet layout for the All Areas page.

---

lang/en.json
lang/ja.json
src/app/admin/RestaurantPage.vue

オーナー向けレストラン編集画面のデザイン調整です。営業時間部分に追加の説明を入れて、二つ目のフォームを別時間帯として設定することを明確にするためにラベルを追加しました。

Minor design update for Owner Edit Restaurant page.

---

functions/src/functions/order.ts
functions/src/lang/en.ts
functions/src/lang/ja.ts
functions/src/stripe/intent.ts

ユーザーによるキャンセルを、LINE連携しているレストラン側の人に送るようにしました。

Notify cancelled order by user

---

src/app/user/RestaurantPage.vue
src/assets/scss/ownplate.scss

Disabled状態のボタンスタイルを調整しました。また、カートボタン押下時にページ全体を少し暗くするようにしました。

Tweak disabled button opacity.

---

src/app/admin/RestaurantPage.vue

openTimesはarrayですが[1]だけデータが入っている場合や
{start:null, end:null}が入っているケースがあるので、それをfilterします。
時間もstart順で並び替えます。

Fix open times

---

src/pages/index.vue

ホームのレイアウトを変更しました。オーナー向けとユーザー向けの入り口を最初に持ってきてアクセスしやすいようにしています。

Rearrange Home page.

---

src/app/user/Profile.vue

Design update for Profile page.

---

lang/en.json
lang/ja.json
src/app/admin/QRCodePage.vue

Design update for QR code page.

---

src/layouts/default.vue

レストランのメニューページと同様に、ホームページも、Firebase からの authentication 情報を待たずに表示するように変更しました。

quick render for homepage

---

src/app/auth/PhoneLogin.vue
src/app/user/Profile.vue

Profile ページに関わる、細かな変更です。
1. Profileページでユーザーとしてログインし、ページ遷移せずにログアウトすると、自動的にログイン Dialog が始まってしまうバグの修正。
2. Profileページから、ユーザーがアカウントを削除する際の re-login ダイアログの２画面目に名前の入力欄が表示されるのは不要なので、その削除。

Profile page: minor fixes

---

src/app/admin/OrderInfoPage.vue

ユーザー、もしくは、ログインしていないユーザーがオーナー向けのオーダーページを開いた時に 404 error を表示するように変更しました。

not found for admin's order page

---

lang/en.json
lang/ja.json
src/app/admin/ManageLine.vue
src/app/admin/OrderListPage.vue
src/app/auth/LineCallback.vue
src/app/auth/TrackCallback.vue

オーナー向けオーダーリストから遷移できるLINE通知設定ページのデザインをアップデートしました。

Update design for Owner Order LINE Settings page.

---

src/app/user/Profile.vue
src/app/user/RestaurantPage.vue

iPhoneでログイン出来なくなる問題を解決しました。スクロールした画面でCaptcha が表示されると、表示もされず、手動でスクロールも出来なくなってしまうようです。

fix iphone login

---

src/app/user/Restaurant/SharePopup.vue
src/app/user/Restaurant/ShopInfo.vue

昔設定して残っていたstyle="word-break: break-all;"を削除しました。該当箇所はownplate.css内の"word-break: break-word;"でカバーしています。

Remove style="word-break: break-all;".

---

functions/package-lock.json
functions/package.json
functions/src/functions/order.ts
functions/src/lang/en.ts
functions/src/lang/ja.ts
functions/src/models/Order.ts

ユーザーが受け取り希望時間を指定しても、店側が混雑時には注文受理の時に受け取り予定時間を指定できる様にするための準備のPRです。
まずは、ユーザー向けの注文受理のメッセージに、調理完了の予定時刻を含めました。

Message: Pickup time

---

src/app/admin/OrderListPage.vue

sound play if new order exists

---

src/app/admin/Index.vue
src/assets/scss/ownplate.scss

iPhone SEなど小さいスクリーン向けの調整CSSです。

Adjustment CSS for Small Screens

---

src/app/auth/PhoneLogin.vue

invisible reCAPTCHA

---

lang/en.json
lang/ja.json
src/app/admin/OrderListPage.vue
src/assets/scss/ownplate.scss

Add Notification Settings Popup.

---

src/app/admin/Index.vue

オーナー向けトップページで注文ページにアクセスしやすいようPaymentとRestaurantの位置を入れ替えました。

Swap the position of the payment and the restaurant.

---

src/app/admin/OrderListPage.vue

注文通知の音がピコピコ（index=0）にセットされていると、音が出ないバグを修正しました。soundIndex の初期値が０だったために、setSoundFile がされていないためです。初期値を undefined にして対応しました。

fix sound bug

---

src/app/admin/MenuListPage.vue
src/app/admin/Restaurant/RestaurantEditCard.vue

すみません、オーナー向けメニューリスト編集ページで公開されたページへのリンクを追加したいのですが、"restaurantInfo.restaurantId"だとうまく行かないのでしょうか？（MenuListPage.vueの54行目）

Adding a link to the published page in Owner Edit Menu List.

---

src/app/admin/News/List.vue
src/app/user/RootPage.vue

v-for のエレメントに :key= がなくてワーニングが出ていたので、追加しました。

Remove warnings: added missing keys

---

functions/src/functions/order.ts

新たな注文が入った時、および、注文がユーザーによってキャンセルされた時に、`/admins/${restaurant.uid}/private/notification` にドキュメントを set する機能です。

notificaton mechanism

---

nuxt.config.js
src/app/admin/Layout.vue
src/routes.js

/admin/restaurants/:restaurantId
で、共通の仕組みを作れるようにしました。

Admin router

---

src/app/user/Restaurant/ItemCard.vue

Add image popup for menu items.

---

src/app/admin/OrderListPage.vue

「１分おきの再通知音」「ピコピコ」「テスト」部分を「通知サウンド」配下に見せるようにデザインを調整しました。

Tweak Notification Settings design.

---

src/app/admin/Layout.vue
src/app/admin/NotificationWatcher.vue

move NotificationWatcher to component

---

src/app/admin/Layout.vue
src/app/admin/OrderListPage.vue
src/app/admin/SoundConfigWatcher.vue
src/plugins/utils.js

OrderListPage.vueでは、notifications（サウンド設定）の状態の更新だけにして、SoundConfigWatcher.vue側で、設定を元にstoreにセットするように変更しました。
これにより、他画面でも音がなります。

Sound config watcher

---

src/app/admin/Notifications/NotificationSettingButton.vue
src/app/admin/Notifications/NotificationSettings.vue
src/app/admin/OrderListPage.vue

separate notification setting

---

src/app/admin/OrderListPage.vue

オーダー確認ページで、予約可能な日付まで、日付を追加しました。
デフォルトでは今日になるように対応。

update order day list

---

src/app/admin/MenuItemPage.vue
src/app/admin/RestaurantPage.vue

Add Save button to the bottom area too.

---

src/assets/scss/ownplate.scss

Androidデバイス向けにポップアップダイアログの上下マージンを調整しました。

Adjust dialog top&bottom margin.

---

src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

レストラン紹介文を中央揃えから左揃えにしました。
レストランウェブサイトが入力されていない場合はリンク箇所を非表示にしました。

Align description left. Hide URL if not entered.

---

functions/src/functions/order.ts
functions/src/models/Order.ts
lang/en.json
lang/ja.json
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderInfoPage.vue
src/app/admin/OrderListPage.vue
src/app/user/Order/TimeToPickup.vue
src/app/user/OrderPage.vue

レストラン側が混雑状況などに応じて、受付時に受け渡し時刻を調整出来るようにしました。
- ユーザーが注文の際に指定出来るのは、「受け渡し希望時刻」です。
- お店は注文を受け付ける際に、「受け渡し予想時刻」を指定します（指定された時間から２時間以内）。
- ユーザーへの通知には、お店が指定した「受け渡し予想時刻」が通知されます。
- ユーザー・アドミンの個別オーダー画面には、両方の時刻が表示されます（受け付け後）。
- アドミンのオーダーリストは、大きくは「ステータス順」、その中で「受け渡し予想時刻」順でソートしています。

Requested pickup time and estimated pickup time

---

functions/src/index.ts
functions/src/stripe/customer.ts
functions/src/wrappers/stripe/stripeDeleteCard.ts

stripe delete card: Skelton

---

lang/en.json
lang/ja.json
src/app/admin/ManageLine.vue
src/app/admin/MenuItemPage.vue
src/app/admin/MenuListPage.vue
src/app/admin/Notifications/NotificationSettingButton.vue
src/app/admin/Notifications/NotificationSettings.vue
src/app/admin/OrderInfoPage.vue
src/app/admin/OrderListPage.vue
src/app/admin/QRCodePage.vue
src/app/admin/RestaurantPage.vue

Notificationコンポーネントをうまく読み込めなかったのでプレイスホルダーのみ追加しました。`### Put Components Here ###`部分にコンポーネントの追加をお願いします。
また通知設定画面（設定だけではないので「通知」に名称変更）のデザインも未完了注文のある日付のリンクを表示するようにしました。ダイアログ内の本日分は赤色にしてあります。通知ボタンの方はダイアログ内のトータルの数字を出した方が良いと思っています。

Add Notification Nav Bar (Place Holder Only).

---

functions/src/stripe/customer.ts
lang/en.json
lang/ja.json
src/app/user/Profile.vue

ユーザーの Profile ページにカード情報を表示し、そこから消去できるようにしました。

Stripe: Delete card info associated with the user

---

lang/en.json
lang/ja.json
src/app/admin/RestaurantPage.vue

営業時間の「前日コピー」ボタンを追加しました。ボタンを押すと常に前日（月曜日の場合は日曜日）の時間をコピー＆反映することを想定しています。実装の方よろしくお願いします。

Add Copy button for Hours.

---

docs/SOUND.md

Add credit for sound files.

---

lang/en.json
lang/ja.json
src/app/user/Restaurant/ShopInfo.vue

支払い方法の表示をレストラン情報部分に追加しました。実装をお願いします。
https://app.asana.com/0/1170889727491677/1178846954750749

Add Payment Method information (Place Holder Only).

---

functions/src/functions/express.ts
functions/src/lib/stripeLog.ts
functions/tests/stripe_test.ts

stripe connect/disconnectのログも追加。

account deauthorized log

---

lang/en.json
lang/ja.json
src/app/admin/Restaurant/RestaurantEditCard.vue

https://app.asana.com/0/1170889733817798/1181095161143266
オーナーがディレクトリーサービスに申請するためのデザインを追加しました。ステータスは「未掲載」「申請中」「掲載済み」の3つで、「申請中」は「申請を取り消す」ボタン、「掲載済み」は「掲載を取り消す」ボタンを表示する想定です。掲載を取り消す場合は運営側の許可はいらないと思っていますが、確認ダイアログは表示した方がいいかもしれません。実装よろしくお願いします。

Add Directory Request section (Placeholder Only).

---

storage.rules

fix storate.rules

---

src/app/user/Profile.vue

ログインしていない状態でプロフィール画面を開くとエラーが出るバグを修正しました。

check if this.user as well

---

functions/src/stripe/oauth.ts

クライアント側のコードを見る限りは、同じ code で stripeConnect を二度呼ぶはずはないのですが（すぐリダイレクトしています）、万が一なんらかの理由で二度呼ばれた時には、二度目のものは無視するようにコードを変更しました。最後に使った code を/admin/${uid}/system/stripe.code にしまっておき、それが一致するかどうかをチェックしています。
結果として、これまで/admin/${uid}/system/stripe にしまっていたデータは、/admin/${uid}/system/stripe.auth に移動させましたが、これを使っていたのは stripeDisconnect だけだったので、そちらも同時に変更しました。
ちなみに、これまでは stripeDisconnect では、/admin/${uid}/system/stripe にある stripe_user_id を使って deauthorize していましたが、/admin/${uid}/public/payment.stripe にあるデータ（同じデータ）を使うように変更しました。これにより、後方互換が保たれています。
結果として、/admin/${uid}/system/stripe.auth にしまっているデータ（stripe.oauth.token API コールからの戻り値全て）は不要になりましたが、将来使いたくなる可能性もあるかも知れないので、残しています。

Stripe OAuth: Detect re-used code case

---

lang/en.json
lang/ja.json
src/app/admin/Index.vue

https://app.asana.com/0/1170889733817798/1181095161143262
オーナー向けトップページにレストラン一覧への掲載方法と通知音に関する注意書きを追加しました。

Add notes for Owner Top page.

---

src/app/admin/OrderInfoPage.vue

オーナー向けオーダー詳細画面の受け渡し予定時刻周りのスタイル調整です。

Tweak styles for Estimated Time Picker.

---

src/app/admin/Index.vue
src/app/user/Profile.vue
src/pages/index.vue

プロファイルページがユーザー状態の変更にちゃんと対応していなかったので修正しました。

Profile: Watch User

---

src/app/super/AllRequests.vue
src/app/super/Index.vue
src/routes.js

update super index

---

firestore.rules
functions/src/stripe/oauth.ts
src/app/super/AllAdmins.vue
src/app/super/SuperHome.vue
src/plugins/stripe.js
src/routes.js

レストランオーナー(admin)の一覧を表示する画面です。ストライプとの連携などを調べるためです。データベース上で連携していながら、実際には連携が切れている場合には、ID を赤で表示します。

Super User: All admins

---

src/layouts/default.vue

layout/default.vue の中で、エラーを処理していない Promise があったので、catch を追加し、Sentry に送るようにしました。

error handling

---

src/app/admin/Restaurant/RestaurantEditCard.vue

onSnapshot の detach が抜けていたので追加しました。

fix onSnapshot Leak

---

lang/en.json
lang/ja.json
src/app/user/RestaurantPage.vue

https://app.asana.com/0/1170889727491677/1181354059885889
オーナー向けプレビューメッセージを追加しました。

Add message for Owner Preview.

---

src/layouts/default.vue
src/store/index.js

- 立ち上がり時に、Firebox Private Browsing Mode を認識して、this.$store.state.isFirefoxPBM にセットします。
- In progress...

WIP: detect Firefox Private Browsing Mode

---

src/app/admin/MenuItemPage.vue

https://app.asana.com/0/1170889733817798/1181905837434529
商品説明文のフォームをテキストエリアにしました。

Use textarea for Item Descriptions form.

---

src/plugins/utils.js

modify isLocaleJapan

---

src/layouts/default.vue

通知が来た時に、ヘッダーを点滅させるようにしました。
これをベースにわかりやすくしてください。

flash header while sound playing

---

src/app/user/Order/OrderInfo.vue

Minor design fix for tip buttons

---

src/layouts/default.vue

通知用Flashをアップデートしました。ページをスクロールしていても見えるようにバナーを`position: fixed;`で表示しています。またCSSアニメーションで点滅させているので`flashStyle()`は未使用になっています。

Add Notification Flash Banner

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/SharePopup.vue
src/app/user/RestaurantPage.vue

商品カードにシェアボタンを追加しました（ダイアログのテンプレートはレストランと共通です）。どこに配置するか悩みましたがカードが展開された時に表示されるようにしてあります。

Add Share button to Item card

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/RestaurantPage.vue

menuのurlでアクセスした場合は、画像を開くようにしました。

open image if menu url

---

src/app/super/AllAdmins.vue

fixed typo to stop memory leak

---

src/app/admin/RestaurantPage.vue
src/app/admin/inputComponents/TextForm.vue
src/components/PhoneEntry.vue

prop name として placeHolder と placeholder が混在しているため、Vueのwarningsが出ていたので修正しました。

remove vue warnings

---

lang/en.json
lang/ja.json
src/app/admin/Index.vue
src/app/admin/Payment/PaymentSection.vue

https://app.asana.com/0/1170889727491677/1182702776006777
オーナー向けトップのStripe部分を受け取り払い部分のデザインを明確に分けました。

Design update for Owner Home Payment section.

---

src/layouts/default.vue

change lang for bot

---

src/app/super/AllAdmins.vue

Super admin 向けの All Admins ページにページングの機能を追加しました。

super:admins paging

---

functions/src/lib/stripeLog.ts

stripe からの callback で job_payments が active になった場合、データベースを自動的にアップデートするロジックです。

handle jcb_payments capabilities

---

src/app/admin/OrderInfoPage.vue

有料オプションの表示が、レストラン・オーナー向けのものとユーザー向けのものとで異なっていたので、修正しました。

fix: priced option display bu

---

lang/en.json
lang/ja.json
src/app/admin/ManageLine.vue

https://app.asana.com/0/1170889727491677/1181317447961387
SafariのプライベートブラウズモードだとLINE連携ができない注書きを追加しました。

Add a note for LINE connection with Safari's Private Browsing Mode.

---

lang/en.json
lang/ja.json
src/app/admin/Index.vue
src/pages/index.vue

https://app.asana.com/0/1170889727491677/1183202843984409
Facebookユーザーグループへリンクを追加しました。

Add Facebook User Group link.

---

src/app/admin/Payment/PaymentSection.vue

Stripe OAuth の際にランダムな state を渡し、それをチェックすることにより、よりセキュアにしました。

Stripe OAuth: state

---

functions/src/functions/super.ts
functions/src/index.ts
functions/src/wrappers/superDispatch.ts

superDispatch

---

firestore.indexes.json
firestore.rules
src/app/super/AdminInfo.vue
src/app/super/Index.vue
src/app/super/Profiles.vue
src/routes.js

Super admin向けの、メアドでユーザーを探すページです（prefix で）。とりあえず探して uid を表示するところまで。

Super: Profiles page

---

lang/en.json
lang/ja.json
src/app/common/Privacy.vue
src/app/common/TermsAdmin.vue
src/app/common/TermsUser.vue
src/app/user/Restaurants/Area.vue
src/app/user/RootPage.vue

最近のクローラーはvueを実行してくれるので、
vueでtitleを設定しました。
他にも必要な箇所があれば、この変更を参考に追加して下さい。

add some header title

---

src/app/user/OrderPage.vue
src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

Payment info

---

functions/src/functions/account.ts
functions/src/index.ts
functions/src/wrappers/accountRegister.ts

accountRegister

---

src/app/admin/Index.vue
src/app/admin/Payment/PaymentSection.vue

emit unsetWarning

---

src/app/user/RestaurantPage.vue

fix restaurantPage title

---

lang/en.json
lang/ja.json
src/app/user/RestaurantPage.vue

オンラインで注文出来ない場合にはcheckout のボタンを押せない。

noPaymentMethodAvailable

---

lang/en.json
lang/ja.json
src/app/user/Restaurant/ShopInfo.vue
src/app/user/RestaurantPage.vue

オンライン注文未対応時のカートボタンのデザインを微調整しました。

Tweak cart button design for noPaymentMethod.

---

src/app/admin/ReportPage.vue

オーナー向け月次報告ページのマイナーデザインアップデート（既存のtableをレイアウト用のcolumsに入れただけ）です。

Minor design update for Owner Report.

---

src/app/user/Restaurant/ShopInfo.vue

Update the texts of the comment.

---

src/app/user/Order/pickupMixin.js

availableDaysと、minimumAvailableTimeが更新されるようになりました。

fix availableDays reactive

---

firestore.rules
src/app/user/Restaurant/SharePopup.vue
src/app/user/RestaurantPage.vue

まずは、like ボタンの実装です。将来は、５段階評価やコメントが入れられるように、
users/{uid}/reviews/{restaurantId} にドキュメントを作り、likes プロパティフラグを on/off しています。
ドキュメント内に restaurantId を持たせているのは、レストラン側から collection query を可能にするためです（document Id は index の対象にならない仕様です）。
お気に入りリストのUIは次のPRで実装します。

Add favorite

---

lang/ja.json
src/app/admin/OrderSuspendPage.vue

注文の一時休止ページですが、文言を少し変更し、日付を追加しました。

display date on suspend page

---

docs/ORDER_STATE.md
functions/src/functions/order.ts
functions/src/stripe/intent.ts

オーダーのstatus変化時のtimestampを入れるようにしました。
ORDER_STATE.md
に、まとめていますが、すでにあるtimeCreatedはそのまま使っています。
timeCanceldはユーザとお店を分けたかったので（uidで判定はできますが）これも残して、他２つを追加しています。（Canceldはtypoですね）
新しいものは、prefix, suffixはorder, Atで統一しています。
その他のtimePlaced等のオーダーに関するtimestampについても
ORDER_STATE.md
に説明を追加しておくと良いと思いました。

Add timestamps when the order status changes

---

src/app/super/AllLogs.vue

nuxt-link to admin info

---

src/components/PhoneEntry.vue
src/plugins/phoneutil.js

phoneutil.js の formatNational の実装のバグを修正しました。ユーザーからの見た目には変化はありません。

fix formatNational

---

lang/ja.json

訂正前：入退店記録
訂正後：COVID-19 Tracking サービス/ 入退店記録
reason 
follow Privacy policy

Update ja.json: from 入退店記録 to COVID-19 Tracking サービス/入退店記録

---

src/app/admin/OrderInfoPage.vue

オーダーページに、注文済み、受付済み、調理済み、受け渡し完了の時刻を表示するようにしました。
キャンセルの方は、別のPRを作ります。

Order times

---

firestore.rules
src/app/operator/AllOrders.vue
src/app/operator/AllRestaurants.vue
src/app/operator/Index.vue
src/plugins/userPermission.js
src/routes.js
src/store/index.js

オペレーター画面を少し実装しました。
レストラン一覧とオーダー一覧を確認できるようになっています。
レストラン一覧の画面の整理と、オーダー一覧のordered-info の修正は必要だと思います。
ordered-info は特に日付等がないのと、リンク先がないので詳細がわかりません。
superからのコピーなので、少し整理して修正していければと思います。

added operator view

---

src/app/admin/OrderInfoPage.vue
src/app/super/AllOrders.vue

admin/operator が All Orders 画面でオーダーの一つを選んだ場合には、レストランオーナー向けのページを開くようにしました。
そのページに、オーダーを受領・キャンセルするボタンなどがありますが、admin/operatorがタップしても失敗することは確認しました。それらを disable することも出来ますが、表示が変わってしまうので、このままでも良いのかなと思います。

Order info admin access

---

functions/tests/express_test.ts
functions/tests/order_test.ts

options関係を実装した時にテストが壊れていたので修正しました。

fix order test

---

functions/src/functions/express.ts

クローラーがJS実行できないときのために、
divにtitileと紹介文入れました。

add body and title to html body

---

lang/en.json
lang/ja.json
src/app/admin/RestaurantPage.vue
src/plugins/constant.js

受け渡し準備期間を最大５日にするものです。
日付や時間を直接入力させると UI が煩雑になるので、radio button で１日、２日などを簡単に選べるようにしました。

minimumCookTime: up to five days

---

src/store/index.js

余計と思われる export const store = new Vuex.Store({}) を外したものです。

remove extra store

---

src/plugins/constant.js

This reverts commit e2d1a5936574024d15e0e606281ce5beb85810d8.

Revert "comment out two/three weeks in advance"

---

src/app/super/AllAdmins.vue

adminの読み込みをarrayの上書きではなく、追加に変更。

fix super admin

---

src/app/super/AdminInfo.vue
src/app/super/AllRestaurants.vue

スーパー管理画面で、
レストランから管理人へリンク追加
管理人情報のページに、名前とメアド表示
を追加しました。

add admin info

---

functions/src/functions/order.ts
lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuItemPage.vue
src/app/admin/Menus/EditCategory.vue

カテゴリー１と２を任意に追加し（文字列の array、レストランごと）、それをメニューにアサインできるようにしました（タグ付ではなく、一つだけ、文字列をコピーします）。
カテゴリーがアサインされたものにオーダーが入った際には、オーダードキュメントの menuItem にもコピーをするようにしました。文字列のコピーなので、後からメニューを変更しても、既存のオーダーは変更されません。

Categories

---

functions/src/functions/express.ts

Google bot say 'Page is not mobile friendly'

add viewport

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuItemPage.vue
src/components/DownloadCSV.vue

とりあえず、指摘していただいた２点を修正したものです。
- 従来のカテゴリーはグループに変更しました
- カテゴリーの中身が空の時は、select そのものを隠すようにしました。

Categories3

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Order/ReportDetails.vue
src/app/admin/OrderHistory.vue
src/components/DownloadOrders.vue

注文履歴ページでも、メニュー別のCSVファイルがダウンんロード出来るようにしました。
良い文言が思いつかないので、とりあえず "Download CSV (details)" としています。

Categories4

---

functions/src/stripe/intent.ts

add orderPlacedAt

---

firestore.indexes.json
firestore.rules
src/app/super/AllPhoneLogs.vue
src/app/super/Index.vue
src/routes.js

add super phone log view

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/RestaurantPage.vue
src/app/user/Order/pickupMixin.js
src/plugins/constant.js

change max pickUpMinimumCookTime to 6 days

---

firebase.json
functions/package.json
functions/src/functions/apis.ts
functions/src/functions/express.ts
functions/tests/express_test.ts

Api for hackathon

---

src/app/admin/ManageLine.vue
src/app/admin/MenuListPage.vue
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderHistory.vue
src/app/admin/OrderInfoPage.vue
src/app/admin/OrderListPage.vue
src/app/admin/OrderSuspendPage.vue
src/app/admin/QRCodePage.vue
src/app/admin/ReportPage.vue
src/app/admin/Restaurant/RestaurantEditCard.vue
src/app/user/Restaurant/ShopHeader.vue
src/app/user/Restaurants/All.vue
src/app/user/Restaurants/Area.vue
src/app/user/RootPage.vue
src/plugins/utils.js

ProfilePhotoをresize使うものに差し替えました。

fix profile image

---

batch/lines.js
firestore.rules
lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Index.vue
src/app/admin/ManageLine.vue
src/app/admin/Restaurant/RestaurantEditCard.vue

Uid on lines

---

src/app/admin/OrderInfoPage.vue

cleanup order statues

---

functions/src/functions/order.ts

clean up order time event

---

src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage.vue
src/plugins/analytics.js

add sendRedunded

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/RestaurantPage.vue
src/app/user/Order/pickupMixin.js
src/app/user/Restaurant/ShopInfo.vue

Temporary closure

---

src/layouts/default.vue

Resize the logo in the menu.

---

.vscode/settings.json
lang/en.json
lang/ja.json
src/app/admin/Menus/ItemEditCard.vue
src/assets/scss/ownplate.scss
src/config/default/ownplate-dev.js

カードの色を変更する代わりに「公開/非公開」のステータス表示をするようにしました。

Tweak the style of Published / Not Published badge

---

functions/src/functions/express.ts

add description meta tag

---

src/components/lp/entranceButtons.vue
src/components/lp/ownplateServiceImage.vue

レストランオーナー及びテイクアウト客用のエントリーポイントのデザインを調整しました。

Update the styles of the entry points

---

src/components/lp/entranceButtons.vue

テイクアウトユーザー向けエントリーボタンのスタイルを調整しました。

Tweak the style of takeout entry point.

---

src/components/lp/userVoices.vue

Tweak the style of the User Voices.

---

lang/en.json
lang/ja.json
src/app/user/Restaurant/ItemCard.vue

同一商品、別オプションの注文を実現するためのPlace Holderです。実装のご検討お願いします。
https://app.asana.com/0/1170889733817798/1172864255632124

Place holder for Add Different Options Item.

---

src/app/user/lp.vue

次回リリースのためのLPコンポーネントの表示/非表示を変更しました。

Edit displayed components for the next release.

---

src/components/lp/userVoices.vue

マイナーなデザイン調整です。（ボタンにシャドウを追加しました。）

Minor style update for the More button.

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/OrderPage.vue

「テイクアウト客SMS認証後に注文がまだ確定していないことを伝える」https://app.asana.com/0/1170889727491677/1199624842175799
SMSログイン後の注文確認画面でオーダーがまだ確定されていないことを伝えるメッセージを追加しました。

Add notes for Order Not Placed Yet

---

src/app/user/Restaurant/ItemCard.vue

「radioタイプのoptionが複数ある場合は、どこまでが１つの選択肢かわからないのを改善」
https://app.asana.com/0/1170889727491677/1199592159755899
背景色を追加しました。

Add a box style for the options

---

lang/ja.json
src/app/admin/MenuListPage.vue

Add toggle button to hide private menu.

hide private menu

---

src/assets/scss/ownplate.scss

Tweak BG color

---

src/app/user/Restaurants/Favorites.vue
src/layouts/default.vue
src/plugins/utils.js
src/routes.js

テイクアウトのお客さんでログインしているときに
サイドメニューに注文履歴を追加しました。

add history button

---

src/app/admin/OrderInfoPage.vue
src/app/admin/RestaurantPage.vue
src/app/user/OrderPage.vue

Update the styles of the Order Memo from the takeout user

---

src/app/user/Restaurant/ShopInfo.vue

Tweak Instagram color

---

functions/src/functions/order.ts
functions/src/stripe/intent.ts

change message notification.

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuListPage.vue
src/app/admin/Menus/ItemEditCard.vue

https://app.asana.com/0/1170889733817798/1199627380401763
オーナーメモ部分のデザイン調整です。その他にも公開/非公開のバッジの調整（背景色が変更になったため）と「全ての商品/公開中のみ」の表示切り替えUIもアップデートしました。

Design updates for Owner Memo, Published Badge, and Toggle UI

---

src/app/user/OrderHistory.vue
src/app/user/Profile.vue
src/app/user/Restaurants/Favorites.vue
src/layouts/default.vue

https://app.asana.com/0/1170889733817798/1199652097370456
グローバルメニューのデザイン調整です。
マイページ内にも「お気に入り」ボタンを追加して、「注文履歴」とともに上部へ移動。
お気に入りページにも「戻る」ボタンを追加。

Update the Global Menu, Profile, and Favorites page.

---

src/app/user/Restaurant/FavoriteButton.vue
src/app/user/Restaurant/ItemCard.vue
src/app/user/Restaurant/SharePopup.vue
src/app/user/RestaurantPage.vue

https://app.asana.com/0/1170889733817798/1199652097370456
お気に入りボタンをSharePopupコンポーネントから切り出しました。

Extract the Favorite button from the SharePopup component

---

lang/en.json
lang/fr.json
lang/ja.json
src/layouts/default.vue

Minor design update for Global Menu

---

src/app/user/RestaurantPage.vue

preview Price

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Order/ReportDetails.vue
src/plugins/utils.js

CSV add memo and option

---

src/app/user/Restaurant/ItemCard.vue
src/app/user/RestaurantPage.vue

update option price

---

nuxt.config.js
package-lock.json
package.json
src/assets/scss/ownplate.scss
src/layouts/default.vue

今後の開発効率を高めるためにTailwind CSS ( https://tailwindcss.com/ ) を導入したいと思います。
インストールして一通り確認したところ、現段階では大きな問題は見られませんでした。
注意点としてはw-, h-系のクラス名がいくつかownplate.cssと被っているのでまとめてアップデートする必要があります。

Install Tailwind CSS

---

src/assets/css/tailwind.css
tailwind.config.js

こちらを参考に ( https://tailwindcss.com/docs/guides/nuxtjs ) `./assets/css/tailwind.css`と`tailwind.config.js`を追加してみました。

Add tailwind config and css

---

src/assets/scss/main.scss

Import Tailwind CSS into main.scss

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuItemPage.vue

add option price preview

---

lang/en.json
lang/fr.json
lang/ja.json
package-lock.json
src/app/user/Restaurant/ShopInfo.vue

ユーザーが商品に直ぐにアクセスできるように店舗詳細を最初は一部だけ表示するようにしました。

User restaurant info

---

lang/en.json
lang/fr.json

Add missing strings

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderHistory.vue
src/app/admin/OrderInfoPage.vue
src/app/admin/OrderListPage.vue
src/assets/scss/orders.scss

カード決済のステータスをStripeアイコンではなくテキストで表示するようにしました。それに伴い若干レイアウトも変更になっています。

Update design for the order card

---

src/app/admin/Order/OrderedInfo.vue

order_status_keys

---

functions/src/functions/order.ts
functions/src/stripe/intent.ts
functions/tests/order_test.ts

注文数の集計について、集計日を受け渡し希望日に変更しました。
受け渡し予定時間は、同じ日で時間調整するので、これで問題ないはずです。

Adjust the time to count sum.

---

functions/package.json
functions/src/functions/line.ts
functions/src/functions/order.ts
functions/src/functions/ses.ts
functions/src/stripe/intent.ts
functions/tests/notify_test.ts
functions/tests/test_helper.ts

Nofitication周りのlocalでテストできるように変更
emailのnotificationを追加します。

Modify notify

---

functions/src/functions/notify.ts
functions/src/functions/order.ts
functions/src/lib/utils.ts
functions/src/stripe/intent.ts
functions/tests/notify_test.ts

separate notification functions

---

src/assets/scss/ownplate.scss
src/layouts/default.vue

Tailwind CSS マイグレーション for default.vue （グローバルメニュー、フッター、言語設定、等）です。
グローバルメニューにレストラ管理ページへのリンクがなかったので追加しました。

Update default.vue with Tailwind CSS

---

src/app/admin/Index.vue
src/app/admin/Restaurant/RestaurantEditCard.vue

デザイン的なごちゃごちゃを減らすためにQRコード＆レポート部分と通知設定部分の順番を入れ替えました。

Switch the order of QR&Report and Notifications

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/RestaurantPage.vue
src/app/admin/inputComponents/HoursInput.vue
src/app/admin/inputComponents/State.vue
src/app/admin/inputComponents/TextForm.vue
src/assets/scss/main.scss
src/assets/scss/ownplate.scss
src/layouts/default.vue

Update Restaurant Details page with Tailwind CSS

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuListPage.vue
src/app/admin/Menus/ItemEditCard.vue
src/app/admin/Menus/TitleCard.vue
src/app/admin/Menus/TitleInput.vue
src/app/admin/Notifications/IncompleteOrders.vue
src/app/admin/Notifications/NotificationSettingButton.vue
src/app/admin/Notifications/NotificationSettings.vue
src/app/admin/RestaurantPage.vue
src/components/Price.vue
src/layouts/default.vue

オーナー側のメニュー一覧ページ（+オーダー通知設定ポップアップ）をアップデートしました。

Update Admin Menu List page with Tailwind CSS

---

src/app/auth/ResetPasswordPage.vue
src/app/auth/SignInPage.vue
src/app/auth/SignUpPage.vue
src/app/user/Profile.vue
src/app/user/RestaurantPage.vue

ログイン周りのTailwind CSSマイグレーションです。

Update the Profile, Sign In/Up, and Password Reset page with Tailwind CSS

---

functions/src/functions/notify.ts
functions/src/lang/en.ts
functions/src/lang/ja.ts

Email通知のテンプレートを微調整しました。すみません、フォーマッターのせいで変更箇所が多く見えますが、
> const message = `${t(messageId)} ${orderName} ${restaurantName}`;
の文字列の入れ替えだけです。

Tweak email notification template

---

src/app/admin/Order/OrderedInfo.vue
src/app/user/OrderHistory.vue

ユーザーの注文履歴画面でローカル時間に影響されないソートにしました。また、時間だけでなく日付も表示してあります。

Add date and Change sort by orderPlacedAt for User Order History

---

src/app/admin/ManageLine.vue
src/app/admin/News/Article.vue
src/app/admin/News/List.vue
src/app/admin/News/ListItem.vue
src/app/admin/RestaurantPage.vue
src/layouts/default.vue

Update Admin News and LINE pages with Tailwind CSS

---

lang/ja.json

確認用QRCodeを飲食店確認用QRCodeに変更

---

src/app/admin/Order/ReportDetails.vue
src/app/admin/OrderHistory.vue
src/app/admin/ReportPage.vue
src/components/DownloadOrders.vue
src/layouts/default.vue

アドミン用の全オーダー履歴とレポートページのCSSをアップデートしました。

Update Admin Order History page and Report page with Tailwind CSS

---

src/app/admin/MenuItemPage.vue
src/app/user/Restaurant/ItemCard.vue
src/plugins/utils.js

管理系のoptionに外税計算の場合の消費税を含めてpreviewするようにしました。
合わせてユーザ系の関数も少し整理しています。

Added tax calculation to option menu on admin view

---

functions/src/functions/ses.ts

Emailの送信名が「omochikaeri」になっていたので「おもちかえり.com」にしました。

Update the name of the sent from

---

src/layouts/default.vue

すみません、一つTailwindのハックを入れ忘れていました。。

Add Tailwind Hack

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Restaurant/RestaurantEditCard.vue

レストランの並び替えボタンを削除ボタンともにカードの下に移動しました。（メニューの商品並び替えと同じようなUIに揃えました。）
商品別名の文言も少し変更してあります。

Change the location of the sort and delete buttons

---

src/app/user/Restaurant/ItemCard.vue
src/layouts/default.vue

Add item name and price to the image popup

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/RestaurantPage.vue

`Select a date`のi18n対応と営業時間の必須マークを追加しました。

Add i18n for "Select a date" and Required mark for Hours

---

firebase.json
functions/package.json
functions/src/functions/express.ts
functions/src/functions/smaregi.ts
functions/tests/express_test.ts

スマレジ対応のテストのため、webhookを開発環境で必要なのでここだけ先にマージします。
(hostingの設定が関係するので、他のPRがマージされると上書きされるため）

add smaregi webhook skelton

---

firestore.indexes.json
firestore.rules
functions/package-lock.json
functions/package.json
functions/src/functions/subAccount.ts
functions/src/index.ts
functions/src/lib/utils.ts
functions/src/wrappers/subaccount/accept.ts
functions/src/wrappers/subaccount/deny.ts
functions/src/wrappers/subaccount/invite.ts
lang/ja.json
package.json
src/app/admin/Index.vue
src/app/admin/Messages/MessageCard.vue
src/app/admin/SubAccounts/Account.vue
src/app/admin/SubAccounts/Accounts.vue

Admin sub account5

---

src/assets/scss/customize.scss

BulmaのTailwindCSSを上書きしてしまう問題のWorkaroundです。

Workaround for Bulma spacing helpers

---

firebase.json
functions/src/functions/order.ts
functions/src/lib/utils.ts
functions/src/stripe/intent.ts
lang/ja.json
src/app/admin/OrderInfoPage.vue
src/app/user/Order/OrderInfo.vue
src/app/user/OrderPage.vue
src/plugins/commonUtils.js

Web
Add shipping fee to total price on the customer and the shop views
Function
Add shipping to the price calculation
Supports shipping post both web preview and Function when order details are changed.

Shipping cost

---

nuxt.config.js
src/app/user/OrderPage.vue
src/app/user/Restaurant/ItemCard.vue
src/app/user/RestaurantPage.vue
src/app/user/RestaurantWrapper.vue
src/routes.js

- routerのnestしたroutingのサポート
- user側のrestaurant pageとorder pageの共通処理をまとめた
- 決済完了前に領収証が表示されていたので修正

add RestaurantWrapper

---

lang/ja.json

たった一文字だけなのですが、気になったので修正してみました。

fix message

---

.gitignore

FOR LOCAL ENV.
for doing after `cp src/config/default/ownplate-dev.ts src/config/project.ts`

add src/config/project.ts to gitignore

---

src/app/user/Restaurant/Category.vue
src/app/user/Restaurant/CategoryIcon.vue
src/app/user/RestaurantPage.vue

・カテゴリー部分のレイアウトのベースを変更
・フローティングボタンのデザイン変更
上記を行いました。
よろしくお願いいたします。

カテゴリー部分のレイアウト変更

---

src/app/user/Restaurant/Cart.vue
src/app/user/Restaurant/CartItem.vue

カート部分レイアウト変更を行いました。
よろしくお願いいたします。

Change cart layout

---

src/app/user/Restaurant/Cart.vue
src/app/user/Restaurant/CartItem.vue

要素がボタンに被る問題を修正しました。
よろしくお願いいたします。

Update cart (issue#43)

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/MenuListPage.vue

カテゴリ一覧に戻るためのボタンを追加しました。
よろしくお願いいたします。

管理画面カテゴリボタンの追加

---

src/app/admin/AdminHeader.vue
src/app/admin/Notifications/NotificationSettingButton.vue
tailwind.config.js

ヘッダーの調整(issue#72)

---

src/app/user/Restaurant/Cart.vue
src/app/user/Restaurant/CartButton.vue
src/app/user/Restaurant/CategoryIcon.vue

issue#83対応のためのレイアウト調整を再度行いました。よろしくお願いいたします。

カート画面のレイアウト調整

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/Restaurant/MoPickUp.vue
src/app/user/RestaurantPage.vue

予約注文/ピックアップのラジオボタンのデザイン変更を行いました。
よろしくお願いいたします。

ピックアップボタンのデザイン変更

---

lang/en.json
lang/fr.json
lang/ja.json
src/components/App/SideMenuMo.vue

サイドメニューにFAQへの遷移するリンクを追加しました。よろしくお願いいたします。

サイドメニューにFAQを追加

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/common/FAQMo.vue

トップへ戻るボタンを追加しました。よろしくお願いいたします。

トップへ戻るボタンの追加

---

src/app/admin/RestaurantPage.vue

管理画面のmarginが崩れている箇所について、レイアウト調整を行いました。よろしくお願いいたします。

管理画面レイアウト調整(issue #297)

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/RestaurantPage.vue

ローカライズされていなかった部分を変更しました。よろしくお願いいたします。

localize text

---

lang/ja.json
src/app/admin/MenuListPage.vue

しきい値表記部分のレイアウトを調整しました。よろしくお願いいたします。

しきい値表記 (issue #274)

---

lang/ja.json
src/app/admin/AdminHeader.vue
src/app/admin/Notifications/NotificationSettingButton.vue

個別店舗用、休止設定機能のUIデザインを実装しました。ご確認よろしくお願いいたします。

休止設定のUIデザイン

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/MoIndex.vue
src/app/user/Restaurant/MoPickUp.vue

・moトップページ
・mo店舗ページ
上記の文言変更を反映させました。よろしくお願いいたします。

文言変更 (issue#313)

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/RestaurantPage.vue

在庫ありのみ表示するトグルボタンを追加しました。よろしくお願いいたします。

絞り込みトグルボタンの追加 (issue#318)

---

src/app/user/Restaurant/MenuMo.vue

お取り寄せ側の在庫ありを非表示にしました。よろしくお願いいたします。

fix design (#337)

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/admin/Index/EmailVerify.vue

管理画面、メールアドレス認証メッセージ部分のデザインを更新しました。よろしくお願いいたします。

認証メール (issue #347)

---

src/app/admin/Index/MailMagazine.vue
src/app/admin/Index/Restaurant.vue
src/app/admin/Index/Smaregi.vue
src/app/admin/Index/SubAccount.vue
src/app/admin/Payment/PaymentSection.vue

マージンの調整やスタイルの統一を行いました。よろしくお願いいたします。

管理画面トップのデザイン調整

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/MoIndex.vue
src/app/user/RestaurantPage.vue

サービス終了店舗用のテキストを追加しました。よろしくお願いいたします。

テキスト追加（issue #368）

---

lang/en.json
lang/fr.json
lang/ja.json
src/app/user/Restaurant/MoPickUp.vue
src/app/user/RestaurantPage.vue

・ピックアップ切り替えボタン
・在庫あり絞り込みボタン
上記のボタンのスタイル変更を行いました。よろしくお願いいたします。

スイッチのデザイン修正 (issue #357,367)

---

src/app/user/Restaurant/CategoryIcon.vue
src/app/user/Restaurant/SubCategoryModal.vue
src/app/user/RestaurantPage.vue

・サブカテゴリページ
・フローティングのカテゴリボタン
上記のデザイン変更を行いました。よろしくお願いいたします。

サブカテゴリ関連のデザイン変更 (issue # 362)

---

src/app/user/RestaurantPage.vue

メニューアイテムのレイアウト崩れを修正しました。よろしくお願いいたします。

Fix layout

---

src/app/user/MoIndex.vue
src/app/user/campaign/202301.vue

余白と画像サイズの微調整を行いました。よろしくお願いいたします。

Fix margin and image size

---

src/lib/pdf/pdf2.ts

pdfのレイアウトを調整しました。よろしくお願いいたします。

Modify layout for pdf (#378)

---

src/app/user/Mo/MoPage202303Spring.vue
src/app/user/Mo/MoPageMenu.vue

キャンペーンページのレイアウト

---

src/app/user/OrderPage/BeforePaid/StripeCard.vue

カード入力欄の調整(#469)

---

src/app/user/Mo/MoPage202303Spring.vue
src/app/user/Mo/MoPageMenu.vue
src/app/user/Mo/MoSetBanner.vue

セット販売キャンペーンページを修正しました。よろしくお願いいたします。

Update set campaign page

---

src/app/admin/RestaurantPage.vue

カレンダーのレイアウト崩れを修正しました。よろしくお願いいたします。

Fix layout (#522)

---

src/app/admin/Order/OrderedInfo.vue
src/app/admin/OrderInfoPage.vue
src/app/user/OrderPage/BeforePaid.vue
src/app/user/OrderPage/OrderInfo.vue
src/app/user/Restaurant/Cart.vue
src/app/user/RestaurantPage.vue

ディスカウント関連のデザインを実装しました。よろしくお願いいたします。

Design for discount

---

src/app/admin/Discount/DiscountHistory.vue
src/app/user/OrderPage/OrderInfo.vue
src/app/user/Restaurant/Cart.vue
src/app/user/Restaurant/PromotionMessage3.vue
src/app/user/Restaurant/PromotionMessage4.vue
src/app/user/Restaurant/PromotionMessage5.vue
src/app/user/RestaurantPage.vue

・店舗トップページ案内文(フローティング)
・カート画面
・注文確認画面
・管理画面履歴
上記の文言、スタイル変更を行いました。よろしくお願いいたします。

Update design for discount

---

src/app/user/Mo/MoFukubukuroBanner.vue
src/app/user/Mo/MoPage20230701.vue
src/app/user/Mo/MoPageMenu.vue
src/app/user/RestaurantPage.vue

・店舗ページへのバナー追加
・LPの価格表記部分の修正
上記を行いました。よろしくお願いいたします。

Add banner and fix layout

---

src/app/user/MoIndex.vue

MOトップページの画像を変更しました。よろしくお願いいたします。

Update hero image

---

src/app/admin/Discount/Discount.vue

Vue2版だと問題なかったのですが、Vue3ブランチだと以下のようになります。
以下のように修正しました。

fix discount layout

---

src/app/auth/SignInPage.vue
src/components/App/SideMenu.vue
src/components/lp/adminServiceIntroduction.vue
src/components/lp/goToAdminLP.vue
src/components/lp/goToUserLP.vue
src/components/lp/searchRestaurant.vue
src/lang/en.ts
src/lang/fr.ts
src/lang/ja.ts

・トップページのレイアウト調整
・不足してた部分のローカライズ
・サイドメニューの変更
上記を行いました。よろしくお願いいたします。

Toppage design3

---

src/assets/css/main.css

https://singularitysociety.slack.com/archives/C0107RHEVM2/p1703294428916589?thread_ts=1703291968.728699&cid=C0107RHEVM2
Fixed the sidebar position issue.

Fix sidebar position

---

src/assets/css/main.css

https://singularitysociety.slack.com/archives/C0107RHEVM2/p1703803687618499
Added workaround CSS for Bulma and Oruga input field.

Add workaround CSS

---

src/app/admin/Restaurants/Index.vue
src/config/constant.ts
src/lang/en.ts
src/lang/fr.ts
src/lang/ja.ts

こちらの文言だけで伝わりそうでしたら、ツールチップは不要かもです。

Localization of the name saving feature

---

src/app/admin/AllOrders.vue
src/app/admin/Index.vue
src/app/admin/Restaurants/Line/Index.vue
src/app/admin/Restaurants/ReportPage.vue
src/app/super/AllOrders.vue
src/app/super/Restaurants.vue
src/app/user/OrderPage/UserCustomerInfo.vue
src/app/user/RestaurantPage.vue

for eslint

---

src/app/admin/Index/Restaurant.vue

https://github.com/SingularitySociety/omochikaeri-docs/issues/88
こちらのページでの修正を行いました。
http://localhost:3000/admin/restaurants

ボタン下の四角いシャドーの修正

---

src/app/admin/Restaurants/Index.vue
src/app/admin/Smaregi/Index.vue

レイアウトを修正しました。
また、Validationチェックで「*お店の指定が重複しています」が赤くならない（以下のコードが効いていない）ので、バックログにチケットを追加しておきます。
```
<o-select
v-model="selectedRestaurant[k]"
:class="
selectedRestaurant[k] && duplicateElement[selectedRestaurant[k]]
? 'border-2 border-solid border-red-700'
: ''
"    
>
```
border-red-700 のところ

Fix sumaregi layout

---

src/components/Button/Cancel.vue
src/components/Button/Submit.vue

- remove the button of the modal dialog on this page:
http://localhost:3000/u/profile

remove shadow under buttons

---

src/components/Button/Cancel.vue

それっぽい色を設定していましたが、他のボタンと合わせるようにしました。

fix button color

---

src/assets/css/main.css

背景色の上書きがきいていなかったので、スタイル記載の場所を移動しました。

fix sidebar backgroud color

---

src/assets/css/main.css
src/assets/scss/bulma.scss

- サイドバー背景色の修正
- 不要モジュール削除
- モジュール削除によるバリデーションアイコンの位置修正

Bulma.scss 調整

---

src/app/user/Restaurant/ShopInfo.vue

Reverting this commit:
https://github.com/Nakajima-Foundation/ownplate/commit/0823af996b99e80c7b2acd317c2ca7eb5f038823

fix vite warning

---

package.json
src/components/Map.vue
yarn.lock

This pull request replaces [Vue3 Google mpas](https://vue-map.netlify.app/) with [vue3-google-map](https://www.npmjs.com/package/vue3-google-map).

replace google map

---

README.md
src/app/auth/SignUpPage.vue
src/assets/css/main.css
src/lang/en.ts
src/lang/fr.ts
src/lang/ja.ts

ボタンの枠線を非表示にするなど、デザインを修正しました。
入力項目は、名前の欄にメッセージやアイコンを追加しました。
また、メールの欄は未入力のときも成功のアイコンが出ていたのでなくしました。
README.md も少し修正しました。

fix: change inactive button design and field warning

---

src/components/Map.vue
src/config/default/ownplate-dev.ts
src/config/default/ownplate-jp.ts

Advanced Markerに変更するPRです。
他の箇所も修正する予定です。
　　/app/user/Restaurant/Delivery.vue
　　/app/admin/Restaurants/Index.vue
　　/app/admin/Restaurants/OrderInfoPage.vue
　　/app/user/OrderPage/BeforePaid.vue
　　/app/user/OrderPage/BeforePaid/Map.vue
　　/app/user/Restaurant/Delivery.vue
　　/components/CustomerInfo.vue
　　/components/Map.vue 済み

marker to advanced marker

---

src/app/auth/Actions/ResetPassword.vue

- Replace orga ui button component with tailwind classes in password reset page
- Maintain existing functionality while updating UI framework

migrate reset password button from orga ui to tailwind

---

src/app/auth/ResetPasswordPage.vue

- Replace orga ui next button component with tailwind classes in email input form
- Maintain existing functionality while updating UI framework

Refactor/reset password email next button UI

---

src/app/auth/SignInPage.vue

- Replace ui next button component with tailwind classes insignia page.
- Maintain existing functionality while updating UI framework.

Refactor/signin page next button UI

---

src/app/admin/Restaurants/Delivery.vue

- Replace orga ui next button component with tailwind classes in email input form
- Maintain existing functionality while updating UI framework

Refactor save button ui in delivery setup page

---

src/app/admin/Restaurants/Index.vue
src/lang/en.ts
src/lang/fr.ts
src/lang/ja.ts

Replace the static Japanese content with a template and define appropriate wording

internationalizaion

---

src/app/admin/Index/Footer.vue
src/app/user/Restaurant/SharingButtons.vue
src/components/App/Footer.vue
src/components/lp/link.vue

- add (Twitter) next to X icon
- remove mail icon from note

update brand name (x and note)

---

src/app/admin/Index/Partners.vue
src/app/admin/Notifications/NotificationSettings.vue
src/app/admin/Restaurants/Line/Index.vue
src/app/admin/Restaurants/MenuItemPage/EditCategory.vue
src/app/admin/Restaurants/OrderInfoPage.vue
src/app/admin/Restaurants/Wrapper.vue
src/app/user/OrderHistory.vue
src/app/user/OrderPage/BeforePaid/StripeCard.vue
src/app/user/Profile/DeleteAccount.vue
src/app/user/Restaurant/FloatingBanner.vue
src/app/user/Restaurant/Menu.vue
src/app/user/Restaurant/SharePopup.vue
src/app/user/RestaurantPage.vue
src/app/user/TransactionsAct/Modal.vue
src/components/App/Footer.vue
src/components/DialogBox.vue
src/components/RequireLogin.vue

This pull request was too large, so I reduced its granularity:
https://github.com/Nakajima-Foundation/ownplate/pull/1443

replace oruga component (o-modal)

---

src/app/admin/Restaurants/Discount/DiscountHistory.vue
src/app/admin/Restaurants/Index.vue
src/app/admin/Restaurants/MenuItemPage.vue
src/app/admin/Smaregi/Store.vue
src/app/user/OrderPage/OrderInfo.vue
src/app/user/Profile/DeleteAccount.vue
src/app/user/Restaurant/FloatingBanner.vue
src/assets/css/tailwind.css
src/components/ImageUpload.vue

```
rg '\bclass=.*\bborder\b' --no-heading| grep -vE 'border-(gray|red|green|blue|indigo|yellow|purple|pink|black|white|neutral|slate|zinc|stone|amber|lime|emerald|teal|cyan|sky|violet|fuchsia|rose|orange|op-teal)'
```

border-color
