Nakajima-Foundation/ownplate

docs/SPEC.md
Found a markdown issue of the line break after the list. "Customers can" is included in the last item.
=> Minor fix for the markdown

firebase.json, functions/package.json, functions/src/functions/express.ts, functions/src/index.ts, functions/tsconfig.json, package.json
ogpサポートしました。
nuxt側でのデプロイスクリプトで、
cp dist/index.html functions/templates/index.html 
と、index.htmlをfunctionsにコピーします。
functionsではexpressで、index.htmlのヘッダーを書き換えて、必要なメタ情報を追加して返すようにしています。
firebase.jsonのrewrite ruleで必要な箇所だけ、functionsを呼ぶようにしています。
どのページでも、結局はindex.htmlを返すので、nuxt側の挙動に影響はなく、初回ロードは遅くなりますが、jsで遷移している限りはパフォーマンスに影響はありません。
nuxtを変更したときに、deployスクリプトを通してfunctionsを変更しないと、ogp該当ページの挙動がおかしくなるので要注意です（これは、CIでデプロイすれば問題なくなります）
=> support ogp

src/components/ItemCard.vue, src/pages/restaurants/menu/_id.vue
counter を itemCard には持たず、親である menu (_id.vue) に orders というオブジェクトで持たせるようにしたものです。この方が、後に実際のオーダーを登録する時にも良いと思います。
=> Itemcard changes2

src/components/ItemCard.vue, src/pages/restaurants/menu/_id.vue
こちらは、PR18 からさらに進めて、$state.totalOrderCount を使わず、itemCard からイベントが来るたびにトータル数を this.orders の情報から計算するようにしたものです。store/index.js の方は（ちゃんと理解できていないので）変更していません。
=> Itemcard change3

functions/package.json, functions/src/common/constant.ts, functions/src/functions/firestore.ts, functions/src/index.ts, src/pages/r/_restaurantId/index.vue, src/plugins/constant.js
ユーザ側の画面でorderをfirestoreに入れるようにしました（開発のために仮で）
firestoreにorderが追加されると、triggerでfunctionが動いて、
オーダーの妥当性のチェック
合計金額の計算
Stripeの処理
statusの更新
をします（ここはまだ未実装）
ユーザ側では、order.idを元に、docをlistenして、statusが更新されたら決済の処理が可能になります。
=> Add trigger

firestore.rules
1. restaurants/{restaurantsId} へのクライアントからの書き込みを禁止しました 
2. firebase.rules を version 2 にアップデートしました（ワイルドカードの扱いが変わりました）
=> rules V2, disallow create

nuxt.config.js, src/assets/scss/main.scss
Material Icon が表示されない問題を解決しました。Buefy をカスタマイズするために "next-buefy" を nuxt.config.js の module から外したのですが、その結果、material icon が import されなくなってしまったのです。Nuxt の黒魔術は便利で良いのですが、こんな風にカスタマイズしたい場合などに逆に手間がかかります。
=> link material icon explicitly

src/pages/admin/restaurants/_restaurantId/orders/_orderId/index.vue, src/pages/r/_restaurantId/order/_orderId/index.vue, src/plugins/utils.js
plugin/utils.vue で mixin している orderId ですが、LoginModal.vue の中のローカルの orderId と被っていました。やはり、この手のものを mixin すると事故が多いので、明示的にインポートするか、個々に定義するのが良いと思います。このケースでは、ここに定義してもたった三行なので、そちらにしました。また、method ではなく、computed にしています（２度目はキャッシュが使われます）。
=> removed orderId mixin

src/layouts/default.vue, src/pages/admin/restaurants/index.vue, src/plugins/userPermission.js
ユーザーがログインしているかいないかが判明するまでは、nuxt を読み込まないようにしました。
=> v-if on nuxt

src/components/OrderedInfo.vue, src/pages/admin/restaurants/_restaurantId/orders/index.vue, src/pages/admin/restaurants/index.vue
admin 用の UI の変更です。
- Restaurants ページの incomplete orders の数字をリアルタイム表示にしました
- Orders ページの表示を時間順（古いもの上）にしました。ソーティングはクライアント側で行なっています。
- どちらのページも、complete (customer_picked_up) は表示しないようにしました。
=> Admin Restaurants View & Orders View

functions/src/checkout/index.ts, package.json, src/pages/r/_restaurantId/order/_orderId/index.vue
=> Checkout Confirm

src/components/ItemCard.vue
オプションがない場合に、空のチェックボックスが表示されてしまうバグですが、根本の問題は、オプションがない場合に、itemOptionCheckbox に[] ではなく [""] が 格納されているためでした（多分、menu editor のバグ）。なので、一つ前のPRは undo して（これは別のバグを導入します）、この問題を回避するために、[""]だった場合には、[]  として扱うように変更しました。
=> work-around special option

nuxt.config.js
LOCALE=jaでdefaultにlocaleを変更できるようにしました。
日本サイトはja指定にします。
この設定をみて、通貨などの単位もlocaleにあわせます。
日本のサービスは、日本語でも英語でも、円、
米サービスはドルになります。
=> can change default locale

functions/src/functions/system.ts, functions/src/index.ts, functions/src/stripe/utils.ts, src/app/user/Order/OrderInfo.vue, src/app/user/Order/StripeCard.vue, src/app/user/OrderPage.vue, src/layouts/default.vue, src/plugins/constant.js, src/plugins/stripe.js, src/store/index.js
- 立ち上がり時にサーバーから systemGetConfig でサーバー側の config を取得するようにしました。現時点では region のみです。
- 取得した serverConfig は、$store.state.server にしまっています
- store の getter.stripeRegion でサーバーから取得した region を利用して、region-specific な Stripe のオプションを返すようにしています（ローカルで region を設定するように変更した場合は、ここを変更します）
- Stripe への hidePostalCode オプションはそちらを利用しています。その結果、郵便番号の入力は、us の場合のみ要求されます。
=> Server config: Region-specific Stripe option

functions/src/functions/order.ts, functions/src/stripe/intent.ts, src/app/admin/Order/OrderedInfo.vue, src/app/admin/OrderInfoPage.vue, src/app/user/OrderPage.vue, src/assets/scss/orders.scss
Order object に Stripe の state (pending, confirmed, canceled) をセットするようにしました。これは UI 表示のためです。
クレジットカードの明細に、オーダー番号、店の名前、電話番号を表示するようにしました。
=> Sprite state, description

functions/src/stripe/intent.ts
Adminのアカウントに Stripe が紐づいていない時に、オーダーがキャンセルできないバグを修正しました。
=> handle no stripe gracefully

functions/src/stripe/utils.ts, src/plugins/constant.js, src/store/index.js
ISO3166に従って、region code を大文字にしました（US, JP, EU)。
この方が、language code (en, ja, fr など）とはっきり区別がつくので良いと思います。
=> ISO 3166 country codes

lang/ja.json, src/app/user/OrderPage.vue
1. ステータスの名称を "支払い済み" から "注文済み" に変更
2. レストラン側が課金設定をしてある場合は、支払わずに注文確定することを不可能に
=> Hotfix v031 01

src/app/user/Order/OrderInfo.vue, src/plugins/constant.js
The default tip and tip options are now coming from stripeRegion. 
Hide the whole tip section (and extra total) if options is an empty array (JP).
=> Region-specific tip

functions/src/functions/order.ts, functions/src/stripe/intent.ts, src/app/user/Order/TimeToPickup.vue, src/app/user/OrderPage.vue, src/config/default/ownplate-dev.js, src/plugins/dateUtils.js, src/plugins/utils.js
顧客が注文を受け取る時間を指定できるようにしました。
時間の単位は１０分で、開店から閉店の１０分前までが指定できます。
閉店時でも予約が出来、３日後までの予約が可能です。
現在時刻から最低でも25分必要です。
デフォルトでは、予約可能な時間の先頭のものが選ばれます。
オーダーの表示側にも若干の変更が必要ですが、その変更は次のPRで行います。
「10分単位」「３日後まで」「最低25分」などのパラメータは、後でレストランごとのカスタマイズが出来るように computed props として切り離してあります。
=> Pickup Time

src/layouts/default.vue
QRコードで直接開かれるレストランのページだけは、Firebaseのユーザー認証を待たずに表示するように変更しました。フォーマットの都合で余計は diff が作られてしまいましたが、実際の変更は、isReadyToRender() の部分だけです。
=> quick render for restaurant page

src/assets/scss/ownplate.scss
カートボタンで`<div>`の代わりに`<b-button>`を使用した場合のCSSリセットです。
=> <b-button> CSS reset for the Cart Button.

src/app/auth/LineCallback.vue, src/app/user/OrderPage.vue
ラインの登録が完了し、かつ、公式アカウントと友達になった場合には、データベースに記録し、その情報があれば、「ラインで通知する」ボタンを隠すようにしました。
=> Friend status

src/app/user/OrderPage.vue
オーダーページで、レストランのロゴもしくは名前をクリックすると、レストランのページに戻るようにしました。
=> link back to restaurant page

functions/src/stripe/oauth.ts, lang/en.json, lang/ja.json, src/app/admin/OwnerPage.vue, src/components/DialogBox.vue
1. Alert のボタンを、YesとNoに変更しました。
2. Stripe アカウントの接続を切る際にアラートを出すようにしました
3. 何らかの理由で、Stripeアカウントとの接続が切れてしまっているのに、DBにのみデータが残っているケースに対応するために、Disconnectの際には先にDBを変更するようにしました。
=> Changes to Stripe Disconnect

src/app/user/OrderPage.vue
お店で支払う処理をした後のエラー処理のコードが間違った場所に置かれていました。
=> fix no payment bug

firestore.rules, functions/src/functions/line.ts, functions/src/functions/trace.ts, src/app/auth/TrackCallback.vue, src/app/trace/Record.vue
COVID-19 feature
- 入店・退店レコードをしまう場所を /hash に移しました（/line から）
- /hash 以下にしまう時に、line-uid を sha256 でハッシュ化したものを使うようにしました
- LINE のみでログインしたユーザーの場合でも custome claims に line=line-uid をセットするようにしました（firebase.rules がシンプルで済みます） 
- お店の人用の匿名リスト表示は次のPRで実装します。
- firebase.rules に /line/{userId} ルールが残っていますが、これは次のPRで消します。
=> WIP: Use hashed lineId

functions/src/functions/trace.ts, src/app/trace/Record.vue
退店のイベントが起こった時に、ペアとなる入店情報とのペアリングを行う処理です。これにより、感染者との同時に店にいたかどうかをQueryで調べることが可能になります。ペアリングが成功すると、entry 側に timeLeft が追加され、両方のイベントが processed = true （処理済み）になります。
ペアリングが出来ない場合は、別途、後処理が出来る様に processed=false のままにしてあります。
=> COVID-19, ENTER/LEAVE pairing

src/assets/scss/ownplate.scss
スペースなしの長い英数字文字列によるレイアウト崩れを解消します。
=> Add "word-break: break-all;" to all <div> and <span>

functions/src/functions/order.ts, functions/src/index.ts, functions/src/stripe/customer.ts, functions/src/wrappers/stripe/stripeUpdateCustomer.ts
これはユーザーのカードを覚えるための準備です。
1. 最初にオーダーが作られた時に、stripe 上に customer を作ります（uid と phoneNumber をメタデータとしてセットします）。
2. stripeUpdateCustomer のスケルトンを作りました（次のPRで実装します）。
3. 別件ですが、wasOrderCreated2 のトランザクションにバグがあったので修正しました。
=> Stripe customer

functions/src/functions/account.ts, functions/src/stripe/customer.ts, functions/src/stripe/intent.ts, src/app/user/Order/StripeCard.vue, src/app/user/OrderPage.vue, src/plugins/stripe.js
クレジットカード番号を記憶して再利用出来るようにしました。
- stripe 側に customer を作り、そこに記憶させています
- その時に、brand, last4, exp_month/year だけを /users/{mid}/readonly/stripe にしまっています
- ２度目以降は、brand + last4 を表示して、デフォルトではそちらを使います
=> Stripe: Reuse Credit Card

functions/src/functions/account.ts, functions/src/stripe/customer.ts
アカウントを消去した際に、Stripe 上の customer も消去するコードを追加しました。同時に、Stripe 関連のデータベースのエントリーを消すコードも同じ場所に集約しました。
=> delete customer from Stripe as well

src/pages/index.vue
hideUsersLink で隠す範囲が広すぎたので、変更しました。これでお「客様向けマニュアル」にはアクセスできるようになります。
=> show user manual

src/app/auth/LineCallback.vue
Line連携を最初にした時に、それがすぐにUIに反映されないというバグを修正しました。
データベースを使った古いコード /users/${hid}/private/line を消し、変更後のcustomClaims をアプデートするように変更しました。
=> bug fix: Connect Line for the first time

src/layouts/default.vue
この変更により、state.user と state.claims は常に同時に設定されるため、タイミングによって super-user 向けのページが表示されなかったり、ラインとの連携ボタンが一度表示されてから消えるようなちらつきも無くなります。
=> set user and claims at the same time

lang/en.json, lang/ja.json, src/app/admin/Index.vue, src/app/admin/News/Article.vue, src/app/admin/News/List.vue, src/app/admin/News/ListItem.vue, src/assets/scss/ownplate.scss
お知らせ一覧と記事ページのデザインテンプレートを作成しましたので実装お願いします。
リリースノートを出したいときはGitHub上のRELEASES.mdのHTMLから`<ul><li>`部分をコピーして`<div class="article-list m-t-24">`配下にペーストすればCSSが適用されるようにしています。
=> Add News List and Article templates.

src/app/auth/PhoneLogin.vue, src/app/user/RestaurantPage.vue, src/layouts/default.vue, src/store/index.js
これまで、ユーザーがログイン時に入力した名前は db にしまっていましたが（そのためにオーダーに名前がちゃんと表示されないというバグが出ていました）、firebase の user.displayName を使うことにしました。それにより、user object と db の同期をする必要がなくなりました。
=> use firebase's displayName to store user's name

package-lock.json, package.json, src/app/admin/OrderInfoPage.vue
受け渡し希望時刻→受け渡し予定時刻を実装するための、一連のPRの最初のものです。
orderUpdate に timezone を渡しています。
timezone をサーバー側で required にしたいので、まずはクライアントのみ変更します。
=> pass timezone to orderUpdate

src/app/admin/MenuItemPage.vue, src/app/admin/RestaurantPage.vue
レストラン情報およびメニュー編集における「保存」ボタンと「公開」チェックボックスをページ上部に移動しました。また、「戻る」の代わりに「キャンセル」と表示することによりページの保存忘れを軽減します。
=> Move Save button to the top area.

functions/src/stripe/customer.ts, lang/en.json, lang/ja.json, src/app/user/Order/StripeCard.vue
このPRで、ユーザーがカード情報を「今後の支払いのために保存する」かどうかを選べるようにしました。
この部分の実装は、connected account と customer が関わっているため少し厄介です。
本気で全てのシナリオを完璧にこなすためには、複数のカード情報をcustomerと関連付け、どれを使うか、どれを再利用するか、などの管理が必要になりますが、それをすると、コードもUIも複雑になります。
そこで、２つ目のカードが使われた時には、１つ目のカードの情報は上書きするように（二つ同時に覚えない）ように実装してあります。
今回の変更により、「今後の支払いのために保存しない」ことが可能になりましたが、そのサイドエフェクトとして、１つのカードを保存して使っていたユーザーが、二つ目のカードをたまたま使う必要があり、その時に「今後の支払いのために保存しない」ことを選択した場合でも、１つ目のカードの再利用が出来なくなってしまいます（もう一度カード情報を入れてもらう必要があります）。とても稀なケースなので、これでも十分だと思いますが、念のために書いておきます。
=> Stripe "no save" option

src/app/user/OrderPage.vue, src/layouts/default.vue, src/store/index.js
ページ全体にローディング・アニメーションを表示する仕組みを作りました。
this.$store.commit("setLoading", true or false);
でオン・オフします。まずは、オーダーのキャンセルで使っています。
=> Global loading animation

functions/src/stripe/intent.ts, src/app/admin/OrderInfoPage.vue, src/app/admin/Payment/PaymentSection.vue, src/config/default/ownplate-dev.js, src/config/default/ownplate-eu.js, src/config/default/ownplate-jp.js, src/config/default/ownplate.js
admin 向けのオーダー個別ページで、値段＋Stripeの部分をタップすると、description （新たに order document のプロパティとしてセーブすることにしたもの）で stripe にサーチをかけるようにしました。これにより、特定のオーダーに紐づく Stripe のトランザクションを見つけることが可能にになります。
description をユニークなものにするために、orderId を加えました。
既存のオーダーに関しては、オーダー名（#542 など）でサーチします。
同時に、stripe dashboard へのURLを project.js ファイルで指定するようにしました。これにより、staging の場合のみ test の dashboard を開くことが可能になります。
また、これまで dashboard は target=_blank で開いていましたが、それをするとタブが増えてしまうので、target=stripe で開くようにしました。
=> Stripe link

.vscode/settings.json
Purpose: Add custom settings for the i18n-ally extension (https://github.com/antfu/i18n-ally)
I discovered this extension a couple of days ago, and it drastically improves the developer experience when having to deal with i18n and translations. It also features editing & commenting for i18n all managed with vscode and git! I really encourage you to try it out if you already haven't already
btw, 
sorry if it the extension and the settings are already utilized by the contributors, 
and I may need time to contribute to the source code itself since I haven't come across developing with vue before :)
=> feat: add i18n ally vscode settings

src/app/auth/TrackCallback.vue, src/components/DialogBox.vue
DialogBox.vue で Sentry.captureException に実際の（catch で捉えた）error object を渡すように変更しました。
=> Pass real error object to Sentry

lang/ja.json
https://app.asana.com/0/search/1181523962564153/1178846954750749
「〜あり」だと他のデフォルトオプションが存在する印象を受けるので（例：オンライン決済あり＝オフライン現金払いはデフォルト？）、あり/なしは取ってしまって単純に決済方法のみ記述する方が良い気がします。
=> Tweak copies for Payment Method info in User Restaurant page.

src/routes.js
routes.js で、children のあるノードに名前があるとワーニングが出るので外しました。
=> removed warning

src/app/auth/SignInPage.vue
Sentry に送られてくる"The email address is badly formatted"ですが、これは auth.signInWithEmailAndPasswor の exception が try-await-catch だけでは全部補足出来ないためです（Firebase のバグです）。この PR は、この問題を、then/catch を使って回避するものです。
ついでに、個別の this.isLoading=true/false を this.$store.commit("setLoading", true/false) を置き換えました。
=> auth.signInWithEmailAndPassword bug work around

functions/src/stripe/oauth.ts, src/app/super/AllAdmins.vue
Super の All Admins 画面で、JCB Payment ステータスを表示するようにしたものです。functions の stripeVerify 内部で connected account の information を取得してクライアントに返すように変更して、実装しました。
=> Super: JCB Payment

src/app/user/RestaurantPage.vue
Sentry でレポートされた Cannot read property 'uid' of undefined を解析した結果、別のバグかもしれませんが、存在しない restaurantId を指定した場合にこのエラーがでてしまうことが分かったので修正します。
https://sentry.io/organizations/ownplate/issues/1747142737/?project=5238403&referrer=slack
=> Avoid uid of undefined

src/app/admin/Layout.vue, src/app/admin/Notifications/NotificationSettings.vue
iPad/iPhone でadmin用のレストランページを直接開いた場合で、通知音がオンの場合のみ、Notification Setting のダイアログを自動的に表示するようにしました。
=> auto popup notification settings

functions/src/functions/order.ts, lang/en.json, lang/ja.json, src/app/admin/RestaurantPage.vue, src/app/user/Order/OrderInfo.vue, src/app/user/OrderPage.vue, src/components/Price.vue
内税をちゃんとサポートするように変更しました。
1. 店が指定する値段は税込みの値段です
2. 客には、その値段を税込みの値段として表示します
3. サーバー側では、内税の場合、税金は逆算して求めますが、合計はしません。
4. 客向けのオーダーページには、内税の場合には内税と明記します。
ちなみに、意味合いがこれまでの taxInclude フラグとは違うので、新たなフラグ inclusiveTax を導入しました。
=> Inclusive tax

functions/src/functions/order.ts, lang/en.json, lang/ja.json, src/app/admin/ReportPage.vue
軽減税率が適用されるものとされないものを分類して表示するようにしました。さらに、内税の心付けに関しても、消費税分を明確にしました。
=> Montly Report: Food tax, Alcohol tax, Service tax

src/app/admin/RestaurantPage.vue
@yutaok 
プロフ画像の入力チェック入れました。
空の場合は、
errors[“restProfilePhoto”]が["validationError.restProfilePhoto.empty"]
にセットされます。
(errors[“restProfilePhoto”].length !== 0)
で判定できます。
エラーの表示をお願いします。
=> add image validator

src/app/admin/Layout.vue, src/app/admin/Notifications/Index.vue, src/app/admin/QRCodePage.vue, src/app/admin/Watcher/NewOrderWatcher.vue, src/app/admin/Watcher/NotificationWatcher.vue
権利のないユーザーがレストランページを開こうとした時に、Notification関連のコードのDBへのアクセスがエラーとして Sentry にレポートされてしまうので、エラーをcatchして、console にはエラー表示しながら、無視するように変更しました。
=> Ignore DB errors in various notification UI

src/components/PhoneEntry.vue
ページロード時に電話番号のvalidationが実行されない問題の修正です。
=> fix phone validation

src/app/super/AllOrders.vue
今度こそ正しい治し方です。
timeEstimated が存在する場合はそちらを、そうでない場合（受け付けられていないもの）は timePlaced を表示します。
=> Super: fixed time presentation of orders

src/app/admin/Order/OrderedInfo.vue, src/app/admin/OrderInfoPage.vue
レストランオーナー向けのオーダーの表示の際に、心付けの分を明示するようにしました。
場所としては二ヶ所あります。
- Order のリスト
- 個別 Order
=> Present tip

lang/en.json, lang/ja.json, src/app/admin/Index.vue, src/app/admin/Payment/PaymentSection.vue, src/app/admin/Restaurant/RestaurantEditCard.vue
オーナーホームの警告スタイルをアップデートしました（メニュー0の場合とお支払い未設定の場合）。
お支払い未設定の場合は`v-if="unsetWarning"`を設定していますが、子コンポーネントの`PaymentSection.vue`から`!this.inStorePayment && !this.hasStripe`を受け取る必要がありますので実装の方よろしくお願いいたします。
=> Update waring styles for Menu and Payment.

lang/en.json, lang/ja.json, src/app/user/Restaurant/SharePopup.vue, src/app/user/RootPage.vue
飲食店エリアの下にお気に入りのレストランを表示するようにしました。
query の回数を減らすために、レストラン名とサムネは review ドキュメントにコピーしています。
そのコピーが古くなった場合には、レストランのページを開いたときにアップデートします。
=> List of "liked" restaurants

functions/src/stripe/intent.ts
timeCanceld が timeCanceld となっていたので修正します。
ストライプ付きのオーダーがキャンセルされた場合の、"orderCustomerCanceledAt" / "orderRestaurantCanceledAt" が抜けていたので追加しました。
=> fixed typo

firestore.indexes.json, firestore.rules, functions/src/functions/super.ts, src/app/super/AdminInfo.vue, src/app/super/AllLogs.vue, src/app/super/Index.vue, src/routes.js
Super admin による操作（データベースの変更など）のログを残す仕組みです。
- ログは /admins/{uidSuper}/logs 以下に記録されます（super admin ごと）
- 表示の際には、collection group query を使います
- super admin の操作であることを示す admin フラグを立てています
- admin の uid でサーチできるように、ドキュメントに uidSuper を追加しています 
- cmd にどんなログなのかが文字列で入っています
- setCustomClaim の場合には、uid, key, value を格納していますが、他のログの場合には別のデータを格納することになると思います。
- 表示は cmd ごとに変えることになると思います
- setCustomClaims にタイポがあったので修正しました（ログを取る前なので、後方互換は不要です）。
=> Super logging

lang/en.json
before:     "list": "Trace List"
after:     "list": "COVID-19 Tracking Service/Trace List"
=> Update en.json: follow privacy policy

lang/en.json, lang/ja.json, src/app/admin/OrderInfoPage.vue
レストラン向けの個別オーダーページに、明細を追加しました。
ユーザー向けのオーダーページで使っているのと同じものです。
情報が重複しますが、キッチンで注文を裁く場合には、注文の内容が大きく写真入りで表示された方が良いので、そのままにしています。
=> order details

lang/en.json, lang/ja.json, src/app/admin/OrderInfoPage.vue
レストラン向けのオーダーの詳細ページで、オーダーがキャンセルされていた場合、"キャンセル済み" と表示した上で、キャンセルした時間を表示するようにしました。どちらがキャンセルしたかによって、文言を少し変えています。
=> cancel time

lang/en.json, lang/ja.json, src/app/admin/OrderHistory.vue, src/app/admin/OrderListPage.vue, src/routes.js
レストラン側が、オーダーの全履歴を見ることが出来るようにしました。
- このページへのリンクは、オーダー一覧（ダッシュボード）の一番下に置きました
- 30個ずつページングしています
- snapshot ではなく、get で取得しています
- isSuperView を使って日付も表示しています
- 戻るボタンで、オーダー一覧に戻ります
=> All orders

lang/en.json, lang/fr.json, lang/ja.json, src/app/admin/Order/ReportDetails.vue, src/app/admin/ReportPage.vue, src/components/DownloadCSV.vue, src/components/DownloadOrders.vue
伊藤忠さんからのリクエストの、
【修正①】注文者の記入がない場合は「空欄」ではなく「未記入」と記載（店舗側で「記入漏れ」と勘違いを生まないようにする為）
【修正③】「受注金額」欄、「支払方法」欄「合計金額」を追加（複数のシートを行き来せずに済むようにする為）
を実装したものです（ただし、「合計金額」は実装していません。理由は下に書きます）。
【修正④】受け渡し時刻につき、全ての行（同一注文番号が複数行にわたる場合も）に記載
は既に実装済みですが、これが記載されるのはステータスが受け渡し完了のもののみです。
【修正②】受注数に「合計受注数」を追加（検品時に確認しやすいようにする為）
は計算して無理やり追加することは可能ですが、Excel 上では計算式にはならないので、CVSファイルとして適切なのか、少し疑問です。修正③の「合計金額」も同じ理由で実装していません。
=> Categories5

lang/en.json, lang/fr.json, lang/ja.json, src/app/user/OrderPage.vue
ユーザー向けの注文ステータスページの最後に、お店向けの注文ステータスページへのQRCodeを貼り付けました。本人・注文確認に店舗で使えるし、将来は受け渡しロッカーに使ってもらうことも可能です。
=> Qrcode on orderpage

functions/src/stripe/intent.ts, lang/en.json, lang/ja.json, src/app/admin/OrderInfoPage.vue
注文処理のフローを
　注文済み→受付済み→受け渡し準備完了（ここで課金）
と変更したものです。
変更点は：
1. 状態遷移の変更（クライアントとサーバー）し、order_accepted から直接 customer_picked_up に遷移できるように変更
2. customer_picked_up の表示を「受け渡し準備完了」に変更
3. customer_picked_up に遷移した時に、ユーザーにメッセージを送るように変更
まずはこれで一旦 merge した後に、
4. customer_picked_up を ready_to_pickup に変更
5. orderUpdate 中の 余計なコードの削除
6. 新しい定義の customer_picked_up の追加
の変更をしたいと思います。
=> New order flow

functions/src/functions/order.ts, functions/src/models/Order.ts, functions/src/stripe/intent.ts, lang/en.json, lang/fr.json, lang/ja.json, src/app/admin/Index.vue, src/app/admin/OrderInfoPage.vue, src/assets/scss/orders.scss, src/plugins/constant.js
PR827 に続く変更です。
1. customer_picked_up を ready_to_pickup に変更
2. transaction_complete という新たな状態を追加
3. 状態繊維が可能かどうかを possible_transitions というデータに記述して、クライアントとサーバーの両方で使うようにしました（これが結構大きな変更で、今回の変更で一番リスクの高い場所です）。
ちなみに、（PR827の時点で生じた問題ですが）副作用として、注文履歴を表示した時に、過去のものが「受け渡し準備完了」として表示されてしまいます。この問題を解決するのであれば、バッチを走らせて、ステータスが ready_to_pickup で、かつ、transaction_complete が存在するもの（新しいものには存在しません）を全て transaction_complete に変更してしまうのが良いかも。
=> order state transition

functions/src/functions/order.ts, lang/en.json, lang/fr.json, lang/ja.json, src/app/admin/Index.vue, src/app/admin/OrderHistory.vue, src/app/admin/OrderInfoPage.vue, src/app/admin/OrderListPage.vue, src/app/admin/Restaurant/RestaurantEditCard.vue, src/assets/scss/orders.scss, src/plugins/constant.js, src/plugins/utils.js
admin/{uid}にhidePrivacyのフラグがある場合に、注文処理等の個人情報を隠せる変更の第一弾です。
「受注処理完了」の状態を追加しました。
後の変更で、「受注処理完了」になると注文が見えなくなるので、「受注処理完了」の表示部分は不要ですが、
最初のテストのために追加しました。
このPRの半分くらいが、オーダーのstatusを変更した時間を記録する、timeEventMapping周りのrefactoringです。
気になったのでいろいろと修正しました。
=> Add transaction hide

src/app/user/lp.vue
「ユーザー・コミュニティで助け合い」の直前にもaskButtonsがあってちょっと冗長に見えるのと、ページの最後にはaskButtonsは置いておいた方が良いと思い、ユーザー・コミュニティで助け合い」の後の askButtons を、ページ下（「このサービスについて」の下、「サービスからのお知らせ」の前）に移動しました。
=> LP: move one of addButtons to the end of the page

src/assets/scss/ownplate.scss, src/components/lp/entranceButtons.vue
entraceButton を最新（11/29）のデザインに近づけました。
「お問い合わせ」ボタンの色の扱いについては、とりあえず `ownplate.sccs` の `$op-colors` に`button-inquiries` を追加しています（後日、全体的な色使いの整理の一貫として更新する）。
=> LP: update entraceButton to match the latest design

src/components/lp/entranceButtons.vue
お問い合わせのリンク先がGluepassページだったのでGoogleフォームのページに変更しました。
=> Update the link to the Inquiry form

firebase.json, functions/src/functions/apis2.ts, functions/src/functions/express.ts, functions/src/functions/order.ts, functions/src/lib/utils.ts, functions/tests/express_test.ts
とりあえず最低限動くAPIです。
restaurants/${restaurantId}/private/apikey
にapikeyを入れて、authorizationヘッダーで認証します。
apikeyの発行の仕組みは最後に入れる予定です。
functionsで発行して、発行したときにしか見えないようにします。
apikeyはレストランごとに１つにして、なにか問題があっても削除 or 上書きで古いものは無効にする。
Todoとして、
-  request時のoption等 (limit, startAt, order等)
-  responseにorderのstatus(注文済み、受付済み、受け渡し完了等）
-  time~~~等の時間のデータが不足している。
等々、まだあります。
また、order::wasOrderCreatedで
itemごとに小計をいれて、それを返すようにしようと思います。
=> add api version 2

lang/en.json, lang/fr.json, lang/ja.json, src/app/user/Restaurant/ItemCard.vue
https://app.asana.com/0/1170889727491677/1199359974509710
オプション適用後の価格表示のUIを追加しました。
適用後の価格の反映がよくわからなかったのでお願いします。
=> Add UI for the Options Applied Price

src/app/user/RestaurantPage.vue
カートボタン内の .level でmobileにも適用するのを忘れていました。。（個数と値段の不要な改行を防ぎます）
=> Keep the level class in mobile view

docs/setup-developer-env.md
`VUE_APP_GAPIKey` を渡さなくてもサーバが立ち上がった。
`VUE_APP_CIRCLE_SHA1` は [デバッグログ出力](https://github.com/Nakajima-Foundation/ownplate/blob/61603badcba3b90c159491668319170f7503ff90/src/components/App.vue#L556) で使われている。`VUE_APP_GAPIKey` はリポジトリ内で利用されている箇所を見つけられませんでした。
=> Remove `VUE_APP_GAPIKey`

src/app/user/Restaurant/CartItem.vue
商品名が長い場合に画像サイズの比率が崩れる問題について修正しました。
よろしくお願いいたします。
=> カート内レイアウト崩れの修正(issue#320)

src/assets/css/main.css
以下のバージョンへあげた際のスタイル崩れを修正
@oruga-ui/theme-bulma”: “^0.4.1"
影響箇所：input、textarea
影響画面：ログイン、店情報の変更、商品登録
以下の画面は別途要修正
注文確認のお店へのメッセージ、自動印刷、ディスカウント、デリバリー、スマレジ、サブアカウント
=> add class in main.css

src/assets/css/main.css
以下のバージョンへあげた際に色が黒っぽくなる現象を修正
@oruga-ui/theme-bulma”: “^0.4.1"
影響箇所：サイドバーを開いたときの背景色
=> fix sidebar background-color

src/assets/css/main.css
@oruga-ui/theme-bulma”: “^0.4.3"
Oruga UIののbulmaテーマのVupに伴い、
新バージョンで正常ケースのテキスト色がほとんど黒なので、旧バージョンと同じ緑色にする。
Oruga-UIを主にエラーケースに使用しており、正常ケースで使用している箇所はレアケースで PhoneLogin.vue, PhoneEntry.vueだけ。
=> change success color to green

src/app/user/OrderPage/BeforePaid/TimeToPickup.vue
- The `TimeToPickup.vue` component is only used on this page
- THe `<time-to-pickup>` element is only used on this page
I am not sure why this margin was added. It was causing the design to break, so I removed it.
=> fix alignment of <input> elements

src/app/auth/PhoneLogin.vue
Hopefully, this change will fix the reCAPTCHA verification error.
Additionally, this change ensures that `handleSubmit` and `handleCode` are not called when the cancel button is clicked..
=> fix Recaptcha verification failed - DUPE (auth/captcha-check-failed).
